### ISSUE TITLE
MariaDB log flooded of mysqld_safe messages

### ISSUE THREAD

**Issue by jokerigno** [linuxserver/docker-mariadb#101]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

 Hi all,

I don't know what happened but my log is flooded of this message:

220306 19:20:14 mysqld_safe Logging to '/config/databases/2372ce5ce2c1.err'.
220306 19:20:14 mysqld_safe Starting mariadbd daemon with databases from /config/databases

and now nexcloud, and db in home assistant doesn't work anymore.

I tried the following solution but it didn't work:

docker exec -it mariadb bash
mv /config/log/ /config/log-old/
exit
docker restart mariadb 

## Environment
**OS:** Unraid
**CPU architecture:** x86_64/arm32/arm64 x86_64
**How docker service was installed:** Using unraid template

## Docker logs

220306 19:20:14 mysqld_safe Logging to '/config/databases/2372ce5ce2c1.err'.
220306 19:20:14 mysqld_safe Starting mariadbd daemon with databases from /config/databases

**Comment by j0nnymoe** [comment]
This tends to happen when the container gets killed without cleanly shutting down and corrupts the database.
Do you happen to have automatic updates on?

**Comment by jokerigno** [comment]
Yes. But it never happened anything till now.

How can I fix this?

**Comment by M0rik4mi** [comment]
Issue happens to me on every restart of my Unraid server.

**Comment by j0nnymoe** [comment]
@M0rik4mi likely because when you're restarting, it's not giving enough time for mariadb to exit cleanly.

**Comment by M0rik4mi** [comment]
how can i fix this? How can i delay the shutdown of Unraid?

**Comment by j0nnymoe** [comment]
You really should be shutting down mariadb when other containers have stopped using it, as this is what causes the corruption. Rather than just shutting off your containers all at once.

**Comment by M0rik4mi** [comment]
ok thanks.

is there any way to get an backup of the database after i get into the bootloop?

**Comment by j0nnymoe** [comment]
Only if you've got your own backup's in place.

**Comment by drizuid** [comment]
this is just a normal startup message you'll see every start of mariadb. if you restart the container, you will see it. If it's spamming, your container is likely looping due to some error. you should review the .err file or restore your personally maintained backups.
