### ISSUE TITLE
curl missing from image

### ISSUE THREAD

**Issue by fragtastic** [linuxserver/docker-mariadb#102]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Container should download remote SQL file with `curl` when `REMOTE_SQL` environment variable is configured.

## Current Behavior

Container does not download remote SQL file, since `curl` is not present in the image.

## Steps to Reproduce

1. Set `REMOTE_SQL` environment variable to URL
2. Start container
3. Receive error in log

## Environment
**OS:** Linux
**CPU architecture:** x86_64
**Image:** `linuxserver/mariadb:latest` -> `https://registry.hub.docker.com/layers/linuxserver/mariadb/latest/images/sha256-ebc2d07b11e51e9cf55fe198937c83c884b8869ce38a6140e42ad05f2b3c6d9b?context=explore`

Relevant lines from `/var/run/s6/etc/cont-init.d/40-initialise-db`
![image](https://user-images.githubusercontent.com/420314/158074437-6eeb6dcc-a7a5-46b3-97df-084f458132c8.png)

## Docker logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 02-tamper-check: executing... 
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    911
User gid:    911
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 40-initialise-db: executing... 
Setting Up Initial Databases
/var/run/s6/etc/cont-init.d/40-initialise-db: line 91: curl: command not found
Installing MariaDB/MySQL system tables in '/config/databases' ...
2022-03-13 18:47:49 1 [Warning] Failed to load slave replication state from table mysql.gtid_slave_pos: 1017: Can't find file: './mysql/' (errno: 2 "No such file or directory")
```

**Comment by exSnake** [comment]
Samething happens to me but without any curl error.

I'm running it on WSL2 Ubuntu 20.04

`mariadb    | [cont-init.d] 40-initialise-db: executing...
mariadb    | Setting Up Initial Databases
mariadb    | Installing MariaDB/MySQL system tables in '/config/databases' ...
mariadb    | 2022-04-20  0:10:51 1 [Warning] Failed to load slave replication state from table mysql.gtid_slave_pos: 1017: Can't find file: './mysql/' (errno: 2 "No such file or directory")
mariadb    | OK`

**Comment by fragtastic** [comment]
As far as I can tell this is still not resolved.

**Comment by drizuid** [comment]
curl is **not** missing...
`docker run --rm --name testdb -e PUID=1006 -e PGID=996 -e MYSQL_ROOT_PASSWORD=secretpw -v /tmp/mdb:/config lscr.io/linuxserver/mariadb`

```
 ~ # docker exec -it testdb curl -V
curl 7.79.1 (x86_64-alpine-linux-musl) libcurl/7.79.1 OpenSSL/1.1.1q zlib/1.2.12 brotli/1.0.9 nghttp2/1.43.0
Release-Date: 2021-09-22
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TLS-SRP UnixSockets
```

there may be another issue present, but it isn't with curl not being in the image
