### ISSUE TITLE
Can't initialize db with files containing queries larger than 20kB

### ISSUE THREAD

**Issue by kaysond** [linuxserver/docker-mariadb#103]
I'm trying to migrate my Nextcloud db into the mariadb container but it fails with `ERROR: 1105 Boostrap file error. Query size exceeded 20000 bytes` because I guess there are some large queries. This is may be an upstream "wontfix" because it's been around since at least 2012: https://bugs.mysql.com/bug.php?id=67345

Notably, this issue doesn't occur with the official mariadb image because they load the files differently: https://github.com/MariaDB/mariadb-docker/blob/c0d07be9ad5eb3bc212c6805cc8031308c56e9b6/10.5/docker-entrypoint.sh 
Speicifcally, they're loading each file one by one via the mysql client's stdin rather than using `--init-file`. 

We are concatenating all the files to a temp file which is then passed in via `--init-file` which has the query size limitation 

https://github.com/linuxserver/docker-mariadb/blob/be172c08b0839199084db02653a66c088ae2484a/root/etc/cont-init.d/40-initialise-db#L79-L82

https://github.com/linuxserver/docker-mariadb/blob/be172c08b0839199084db02653a66c088ae2484a/root/etc/cont-init.d/40-initialise-db#L4-L13

**Comment by lha-hockey** [comment]
@kaysond I've made a pull request to be able to load large sql files at container startup (located in /config/dump.files.d/*.sql). I hope this will be merged in next release.

**Comment by kaysond** [comment]
not stale. @lha-hockey - not seeing any PR?

**Comment by kaysond** [comment]
not stale

**Comment by kaysond** [comment]
not stale. planning on making a PR for this at some point...

**Comment by AvrumFeldman** [comment]
Came here to report the same issue. 
`ERROR: 1105  Bootstrap file error. Query size exceeded 60000 bytes`

@lha-hockey Just confirming, per the documentation the files should be `/config/initdb.d` not  `/config/dump.files.d/`
