### ISSUE TITLE
[FEAT] Gracefully failing when cant change owner of /config on nfs

### ISSUE THREAD

**Issue by vonProteus** [linuxserver/docker-mariadb#114]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

i would like to continue starting of server when chown of /config fails

### Reason for change

when you mount /config from nfs chown fails 

### Proposed code change

https://github.com/linuxserver/docker-mariadb/blob/ee9c73d51f2cb6856cb84b0569d115d01f84e3a1/root/etc/s6-overlay/s6-rc.d/init-mariadb-initdb/run#L125 to something like 
```
chown -R abc:abc /config || echo "CAN'T CHOWN MAKE SURE YOU HAVE SET CORRECT ($(id -u abc):$(grep abc /etc/group  | cut --delimiter ':' --fields 3)) OWNER ON /config"
```

**Comment by aptalca** [comment]
Even if it starts, you'll likely have database corruption, which is one of the reasons we don't support config folders on nfs/smb

**Comment by Roxedus** [comment]
This is something we are working to incorporate trough all our images, our nginx based images already does this.

**Comment by vonProteus** [comment]
i am still interested in this

**Comment by thespad** [comment]
The current builds should (relatively) gracefully fail when they can't set permissions on /config.
