### ISSUE TITLE
[BUG] Pulling no matching manifest for linux/arm/v8 in the manifest list entries

### ISSUE THREAD

**Issue by truthsword** [linuxserver/docker-mariadb#126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![](https://i.imgur.com/6v3AuMa.png)

### Expected Behavior

Error "no matching manifest for linux/arm/v8 in the manifest list entries" does not occur.

```
bookstack_db:
    image: "lscr.io/linuxserver/mariadb:latest"
```

### Steps To Reproduce

1. Docker on RaspberryPi (fully updated)
2. Pull command fails on "latest" (see screenshot above)
3. Dropped back to 10.6.1 and all is well

### Environment

```markdown
- OS: RPi
- How docker service was installed:RPi
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "3"
services:
  bookstack_db:
    image: "lscr.io/linuxserver/mariadb:latest"
    container_name: bookstack_db
    environment:
      - PUID=1001
      - PGID=1001
      - MYSQL_ROOT_PASSWORD=maria
      - TZ=America/New_York
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=bookstack
    volumes:
      - "/home/docker/bookstack/mariadb/config:/config"
    restart: unless-stopped
```
```


### Container logs

```bash
No logs as container isn't created with "latest"
```

**Comment by Roxedus** [comment]
Same reason as in your bookstack issue. Please stick to one repository. https://github.com/linuxserver/docker-bookstack/issues/175#issuecomment-1567263889
