### ISSUE TITLE
[BUG] arm32v7-latest

### ISSUE THREAD

**Issue by Creaprog** [linuxserver/docker-mariadb#129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I'm using the image `linuxserver/mariadb:arm32v7-latest` with my Raspberry pi 2 I can see this error : `no matching manifest for linux/arm/v7 in the manifest list entries`

### Expected Behavior

I would like to have the same behavior with the image `linuxserver/mariadb:arm32v7-10.6.13`

### Steps To Reproduce

I have this problem with docker-compose mais we can have the same problem with only Docker. I can't pull an image with a bad architecture

### Environment

```markdown
- OS: Raspbian 32 bits (Processor armv7l) 
- How docker service was installed: I followed the official documentation of Docker
```

### CPU architecture

arm64

### Docker creation

```bash
mariadb:
    image: linuxserver/mariadb:arm32v7-latest
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: xxxx
      MYSQL_DATABASE: xxx
      MYSQL_USER: xxxx
      MYSQL_PASSWORD: xxxx
    networks:
      - xxxx
```

### Container logs

```bash
The docker didn't run, I didn't have any log just `no matching manifest for linux/arm/v7 in the manifest list entries`
```

**Comment by thespad** [comment]
Please note the container [changelog](https://github.com/linuxserver/docker-mariadb#versions) and our [blog post](https://www.linuxserver.io/blog/a-farewell-to-arm-hf).

armhf support has been deprecated for this image and if you wish to continue using it you will need to pull a specific version tag, understanding that it will not recieve any updates or support going forward.
