### ISSUE TITLE
[BUG] #1231 - Variable 'lc_messages' can't be set to the value of 'zh_CN'

### ISSUE THREAD

**Issue by Kings-Github** [linuxserver/docker-mariadb#130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I used docker-compose to install Linux Server/Maria DB and Linux Server/phpmyadmin.

- Mariadb version: 10.11.3(latest)
- Phpmyadmin version: 5.2.1(latest)
- OS:centos7.9

I use the browser to open phpmyadmin to switch Chinese language. The error is as follows:
#1231 - Variable 'lc_messages' can't be set to the value of 'zh_CN'

Repair:
Open the following file in the mariadb directory: custom.cnf

Form：
lc_messages_dir = /usr/share/mysql
lc_messages     = en_US

Fix to:
lc_messages_dir = /usr/share/mariadb
lc_messages     = en_US

### Expected Behavior

It should display Chinese pages normally.

### Steps To Reproduce

null

### Environment

```markdown
centos7.9
```

### CPU architecture

x86-64

### Docker creation

```bash
Linuxserver/mariadb
Linuxserver/phpmyadmin
```

### Container logs

```bash
null
```

**Comment by thespad** [comment]
It looks like every other path is still using `mysql` for backwards compatibility but the newer versions have changed the LC_messages path to `mariadb`.

We'll update the custom.cnf we ship with the image, but it won't update any existing ones.
