### ISSUE TITLE
[FEAT] healthcheck.sh to container image.

### ISSUE THREAD

**Issue by saffrey** [linuxserver/docker-mariadb#141]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Hi team, not sure if this is where to post this github is new to me. 

The official docker container for mariadb has healthcheck.sh. This script allows for healthchecks of the mariadb instance etc. when using it as a dependency for other containers. 

[healthcheck.sh](https://github.com/MariaDB/mariadb-docker/blob/master/healthcheck.sh)

### Reason for change

Improves reliability of stacks.

### Proposed code change

Add the healthcheck.sh script to the linuxserver/mariadb container image.

**Comment by j0nnymoe** [comment]
We have no plans of adding healthchecks to our containers. If deploying with docker compose, you're able to add your own healthcheck that way.

**Comment by saffrey** [comment]
Really just after the healthcheck.sh scrip to be included so one can do exactly as you suggest - this script from mariadb is standard with the package - just needs to be added to your image...

`      healthcheck:
        test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
        start_period: 1m
        start_interval: 10s
        interval: 1m
        timeout: 5s
        retries: 3`

**Comment by aptalca** [comment]
You can add that yourself, too.
