### ISSUE TITLE
Documentation clarification - environment variables

### ISSUE THREAD

**Issue by chelming** [linuxserver/docker-mariadb#143]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Clarification on whether the Database, User, and Password environment variables are required or can be changed after the container is set up.

If I initialize the container with MYSQL_DATABASE, MYSQL_USER, and MYSQL_PASSWORD, will changing them in the future have any effect? Can they be deleted after first run when the database is set up or will removing them remove the database that was created?

### Reason for change

Clarification

**Comment by chelming** [comment]
pls keep open :)

**Comment by j0nnymoe** [comment]
Readme already states those are optional:

```
      - MYSQL_DATABASE=USER_DB_NAME #optional
      - MYSQL_USER=MYSQL_USER #optional
      - MYSQL_PASSWORD=DATABASE_PASSWORD #optional
```
Also a couple mentions here https://github.com/linuxserver/docker-mariadb?tab=readme-ov-file#application-setup that these ENV's specifically for username/passwords are one time only.

**Comment by chelming** [comment]
Being optional doesn't address the question about what happens if you define them on first boot and then subsequently change them. The only call-out is for the root password, but it doesn't mention the DB, user, or (non-root) password.

My assumption is that once the database is created, the env vars won't be used but the docs aren't clear on whether or not that's the case. If that **is** the case, some text like what mongo uses would make that clear:

> When you start the `mongo` image, you can adjust the initialization of the MongoDB instance by passing one or more environment variables on the docker run command line. Do note that none of the variables below will have any effect if you start the container with a data directory that already contains a database: any pre-existing database will always be left untouched on container startup.

**Comment by chelming** [comment]
I'd still like appreciate if the docs were updated with more clarity 😄

**Comment by chelming** [comment]
it'd still make me happy

**Comment by drizuid** [comment]
> I'd still like appreciate if the docs were updated with more clarity 😄

as you were told in https://github.com/linuxserver/docker-mariadb/issues/143#issuecomment-2156816443
your question(s) are already addressed and have been addressed... What exactly are you looking for in terms of clarity? 


![image](https://github.com/user-attachments/assets/e09c82a2-cc72-466c-b74d-d225166b951e)

**Comment by chelming** [comment]
@drizuid that doesn't say anything about the DB or user. If you change them, will a new database be created? a new user created? who knows. it doesn't say 🤷‍♀️

specifically, my reply to the post you quoted are the questions I still have:
> Being optional doesn't address the question about what happens if you define them on first boot and then subsequently change them. The only call-out is for the root password, but it doesn't mention the DB, user, or (non-root) password.
> 
> My assumption is that once the database is created, the env vars won't be used but the docs aren't clear on whether or not that's the case. If that **is** the case, some text like what mongo uses would make that clear:
> 
> > When you start the `mongo` image, you can adjust the initialization of the MongoDB instance by passing one or more environment variables on the docker run command line. Do note that none of the variables below will have any effect if you start the container with a data directory that already contains a database: any pre-existing database will always be left untouched on container startup.

**Comment by chelming** [comment]
I also don't know why the root password keeps getting brought up 😅 I don't say anything about it in my issue or have any questions about it. That's the only one that _does_ say what happens if you change it after the container is initialized.

**Comment by chelming** [comment]
@drizuid thanks for sticking with me ❤️
