### ISSUE TITLE
[FEAT] MariaDB Upgrade Instructions in Log are Unclear

### ISSUE THREAD

**Issue by dyno10** [linuxserver/docker-mariadb#147]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

The command presented in the container log instructing the user to upgrade their database files is incorrect.  

At present:

`mariadb-upgrade -u root -p<password>`

<img width="816" alt="Screen Shot 2024-07-04 at 10 40 19 AM" src="https://github.com/linuxserver/docker-mariadb/assets/166157675/58a9ceee-be0c-4645-b88b-35c31406b059">

### Reason for change

It's a source of confusion for users.

### Proposed code change

The instructions should read:

`mariadb-upgrade -u root -p \`
`       <password>`

This should make it clearer that the password must be provided interactively.  Typing the command as shown in the container logs does not work.  Alternatively, just remove the password tag entirely.

**Comment by j0nnymoe** [comment]
That message is provided by mariadb itself. Not something we control.
