### ISSUE TITLE
[BUG] PR dont's should be written in README

### ISSUE THREAD

**Issue by federico-razzoli** [linuxserver/docker-mariadb#149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the pull request template (the description text box) I read:

"If this is a fix for a typo (in code, documentation, or the README) please file an issue and let us sort it out. We do not need a PR"

However, if I see this message, I already spent time on the PR.

### Expected Behavior

Write the message in README or, even better, have a CONTRIBUTING file.

### Steps To Reproduce

Make a pull request.

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
.
```

### Container logs

```bash
.
```

**Comment by Roxedus** [comment]
There is a contributing file, it is in the place github expects it. https://github.com/linuxserver/docker-mariadb/blob/master/.github/CONTRIBUTING.md, this is also linked in the top of the readme.md file

**Comment by federico-razzoli** [comment]
It's curious that GitHub asks us to put it in a dot directory and not where almost all repositories put it... but who am I to question them. I'm closing the issue.
