### ISSUE TITLE
[FEAT] Images for MariaDB 11 series 

### ISSUE THREAD

**Issue by andrebrait** [linuxserver/docker-mariadb#151]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Add images for MariaDB 11.

11 is now GA and 11.4 is the latest LTS, yet we have no images for those version.

### Reason for change

This one is still in version 10.11, in contrast with the official image which is on 11.4.

**Comment by Roxedus** [comment]
We use the mariadb package in the Alpine package repository, we do not have control of which versions they build for a release of Alpine.

**Comment by andrebrait** [comment]
Oh, got it then. My bad. At least this issue will likely be indexed by search engines and people with similar questions might get this as answer.

Hopefully it gets built for alpine at some point

**Comment by Roxedus** [comment]
The rolling release of Alpine is on 11.4, but this image is based on a stable branch. Once Alpine 3.21 comes, mariadb will upgrade to the version that is in rolling at that point, these usually happens on 6 month intervals.

**Comment by andrebrait** [comment]
So around October or so. No problem. Thanks for the explanation.
