### ISSUE TITLE
[BUG] MariaDB is GPL-2.0 only not GPL-3.0-only

### ISSUE THREAD

**Issue by grooverdan** [linuxserver/docker-mariadb#157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

podman inspect lscr.io/linuxserver/mariadb
```
                    "org.opencontainers.image.documentation": "https://docs.linuxserver.io/images/docker-mariadb",
                    "org.opencontainers.image.licenses": "GPL-3.0-only",
```

https://github.com/opencontainers/image-spec/blob/main/annotations.md

org.opencontainers.image.licenses License(s) under which contained software is distributed as an [SPDX License Expression](https://spdx.github.io/spdx-spec/v2.3/SPDX-license-expressions/).

### Expected Behavior

GPL-2.0-only

### Steps To Reproduce

Look at podman inspect lscr.io/linux/server and compare license to https://github.com/MariaDB/server/blob/main/COPYING.

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
N/A
```

### Container logs

```bash
N/A
```

**Comment by aptalca** [comment]
That label reflects our image's license, which is contained in this repo. It covers our build (Dockerfile) and init logic and all that. It does not apply to and is not representative of any software or dependencies that may be installed in the image.

**Comment by grooverdan** [comment]
The OCI spec on the org.opencontainers.image.licenses "under which contained software is distributed", referring to the image.

You can't redefine this to something you want it to represent (without a OCI approval process to change the standard).

Given the inclusion of both, "GPL-2.0-only AND GPL-3.0-only" is acceptable per https://spdx.github.io/spdx-spec/v2.3/SPDX-license-expressions/#d43-conjunctive-and-operator

**Comment by aptalca** [comment]
I'm not going to argue this any further but I'll just say this. The image contains an entire operating system. It's not just mariadb. There are tons of different pieces of software and code. We're not going to list the licenses of all of them in a label.

Thanks for your concern.
