### ISSUE TITLE
[BUG] container starting issues on QNAP systems

### ISSUE THREAD

**Issue by mammo0** [linuxserver/docker-mariadb#158]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Hello,
the issue is basically the same as https://github.com/linuxserver/docker-swag/issues/514 and probably affects all linuxserver images that are running on QNAP.

Can you apply the workaround from https://github.com/linuxserver/docker-swag/pull/523 to all your images? That would be really nice :)

Hopefully this will be fixed soon by QNAP.

### Steps To Reproduce

Run the container on a current QNAP Container Station

### Environment

```markdown
- OS: QNAP
- How docker service was installed: Container Station
```

### CPU architecture

x86-64

### Docker creation

```bash
default CLI command from README.md
```

### Container logs

```bash
A lot of bad address messages
```

**Comment by j0nnymoe** [comment]
This will likely need to be something changed at QNAP level rather than the containers. We just need to do some investigating of it first.

**Comment by mammo0** [comment]
> This will likely need to be something changed at QNAP level rather than the containers. We just need to do some investigating of it first.

Hello @j0nnymoe
Yes, you are right it's likely a QNAP issue. @thespad provided me the following Discord link: https://discord.com/channels/354974912613449730/1307683867553038417
Unfortunately I can't see the content (I don't have the necessary permissions)

**Comment by thespad** [comment]
The short answer is no, we really don't want to because it will mask *actual* issues that non-QNAP users experience and lead to broken containers that are hard to troubleshoot. We only added the workaround for Swag because a change we made to the init process unintentionally caused previously working containers to break for people experiencing this QNAP bug.

QNAP need to fix this upstream.

**Comment by salvq** [comment]
Hello,

What steps do I need to take to resolve the bad address issue? Is it enough to simply use the image linked here [https://github.com/linuxserver/docker-swag/pull/523#issuecomment-2481285195](url)

I’ve already tried using the image, but the issue persists.

Thanks

`[env-init] CF_TUNNEL_CONFIG set from FILE__CF_TUNNEL_CONFIG
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support the app dev(s) visit:
Certbot: https://supporters.eff.org/donate/support-work-on-certbot

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────


User UID:    1000
User GID:    100
───────────────────────────────────────
Linuxserver.io version: 3.0.1-pkg-c8ade9f4-dev-bfeeaaaa7352746eb3d09cc84c29473837549c7e-pr-523
Build-date: 2024-11-17T14:18:00+00:00
───────────────────────────────────────

using keys found in /config/keys
chmod: changing permissions of '/config/nginx/site-confs': Bad address
chmod: changing permissions of '/config/nginx/site-confs/default.conf.sample': Bad address
chmod: changing permissions of '/config/nginx/site-confs/default.conf': Bad address
chmod: changing permissions of '/config/nginx/nginx.conf.sample': Bad address
chmod: changing permissions of '/config/nginx/nginx.conf': Bad address
chmod: changing permissions of '/config/nginx/authelia-location.conf': Bad address
chmod: changing permissions of '/config/nginx/proxy.conf': Bad address
chmod: changing permissions of '/config/nginx/authentik-location.conf': Bad address
chmod: changing permissions of '/config/nginx/authentik-server.conf': Bad address
chmod: changing permissions of '/config/nginx/ssl.conf': Bad address
chmod: changing permissions of '/config/nginx/ssl.conf.sample': Bad address
chmod: changing permissions of '/config/nginx/authelia-server.conf': Bad address
chmod: changing permissions of '/config/nginx/proxy.conf.sample': Bad address
chmod: changing permissions of '/config/nginx/dhparams.pem': Bad address
chmod: changing permissions of '/config/nginx/resolver.conf': Bad address
chmod: changing permissions of '/config/nginx/worker_processes.conf': Bad address
chmod: changing permissions of '/config/nginx/proxy-confs': Bad address
chmod: changing permissions of '/config/nginx/proxy-confs/guacamole.subdomain.conf': Bad address
chmod: changing permissions of '/config/nginx/proxy-confs/nas.subdomain.conf': Bad address
chmod: changing permissions of '/config/nginx/proxy-confs/router.subdomain.conf': Bad address
chmod: changing permissions of '/config/nginx/proxy-confs/modem.subdomain.conf': Bad address
chmod: changing permissions of '/config/nginx/proxy-confs/homeassistant.subdomain.conf': Bad address
chmod: changing permissions of '/config/nginx/proxy-confs/routerssh.subdomain.conf': Bad address
chmod: changing permissions of '/config/nginx/authelia-location.conf.sample': Bad address
chmod: changing permissions of '/config/nginx/authelia-server.conf.sample': Bad address
chmod: changing permissions of '/config/nginx/ldap-location.conf': Bad address
chmod: changing permissions of '/config/nginx/ldap-server.conf': Bad address
chmod: changing permissions of '/config/nginx/ldap-server.conf.sample': Bad address
chmod: changing permissions of '/config/nginx/cf_real-ip.conf': Bad address
chmod: changing permissions of '/config/nginx/authentik-location.conf.sample': Bad address
chmod: changing permissions of '/config/nginx/authentik-server.conf.sample': Bad address
chmod: changing permissions of '/config/nginx/ldap-location.conf.sample': Bad address
chmod: changing permissions of '/etc/logrotate.d/acpid': Bad address
chmod: changing permissions of '/etc/logrotate.d/fail2ban': Bad address
chmod: changing permissions of '/etc/logrotate.d/lerotate': Bad address
chmod: changing permissions of '/etc/logrotate.d/nginx': Bad address
chmod: changing permissions of '/etc/logrotate.d/php-fpm': Bad address
chmod: changing permissions of '/etc/logrotate.d/php-fpm83': Bad address
Variables set:
PUID=1000
PGID=100
TZ=Europe/Prague
URL=XXXX.eu
SUBDOMAINS=wildcard
EXTRA_DOMAINS=
ONLY_SUBDOMAINS=false
VALIDATION=dns
CERTPROVIDER=
DNSPLUGIN=cloudflare
EMAIL=
STAGING=

chmod: changing permissions of '/defaults/etc/letsencrypt/renewal-hooks/deploy': Bad address
chmod: changing permissions of '/defaults/etc/letsencrypt/renewal-hooks/deploy/10-default': Bad address
chmod: changing permissions of '/defaults/etc/letsencrypt/renewal-hooks/post': Bad address
chmod: changing permissions of '/defaults/etc/letsencrypt/renewal-hooks/post/10-nginx': Bad address
chmod: changing permissions of '/defaults/etc/letsencrypt/renewal-hooks/pre': Bad address
chmod: changing permissions of '/defaults/etc/letsencrypt/renewal-hooks/pre/10-nginx': Bad address
Using Let's Encrypt as the cert provider
SUBDOMAINS entered, processing
Wildcard cert for salvq.eu will be requested
No e-mail address entered or address invalid
dns validation via cloudflare plugin is selected
Certificate exists; parameters unchanged; starting nginx
chmod: changing permissions of '/etc/logrotate.d/acpid': Bad address
chmod: changing permissions of '/etc/logrotate.d/fail2ban': Bad address
chmod: changing permissions of '/etc/logrotate.d/lerotate': Bad address
chmod: changing permissions of '/etc/logrotate.d/nginx': Bad address
chmod: changing permissions of '/etc/logrotate.d/php-fpm': Bad address
chmod: changing permissions of '/etc/logrotate.d/php-fpm83': Bad address
chmod: changing permissions of '/config/log/nginx': Bad address
chmod: changing permissions of '/config/log/nginx/error.log': Bad address
chmod: changing permissions of '/config/log/nginx/access.log': Bad address
chmod: changing permissions of '/config/log/nginx/error.log.2.gz': Bad address
chmod: changing permissions of '/config/log/nginx/error.log.6.gz': Bad address
chmod: changing permissions of '/config/log/nginx/access.log.2.gz': Bad address
chmod: changing permissions of '/config/log/nginx/access.log.3.gz': Bad address
chmod: changing permissions of '/config/log/nginx/access.log.4.gz': Bad address
chmod: changing permissions of '/config/log/nginx/access.log.5.gz': Bad address
chmod: changing permissions of '/config/log/nginx/access.log.6.gz': Bad address
chmod: changing permissions of '/config/log/nginx/error.log.3.gz': Bad address
chmod: changing permissions of '/config/log/nginx/access.log.7.gz': Bad address
chmod: changing permissions of '/config/log/nginx/access.log.8.gz': Bad address
chmod: changing permissions of '/config/log/nginx/access.log.9.gz': Bad address
chmod: changing permissions of '/config/log/nginx/access.log.10.gz': Bad address
chmod: changing permissions of '/config/log/nginx/access.log.11.gz': Bad address
chmod: changing permissions of '/config/log/nginx/error.log.4.gz': Bad address
chmod: changing permissions of '/config/log/nginx/access.log.12.gz': Bad address
chmod: changing permissions of '/config/log/nginx/access.log.1': Bad address
chmod: changing permissions of '/config/log/nginx/error.log.5.gz': Bad address
chmod: changing permissions of '/config/log/nginx/access.log.13.gz': Bad address
chmod: changing permissions of '/config/log/nginx/access.log.14.gz': Bad address
chmod: changing permissions of '/config/log/nginx/error.log.7.gz': Bad address
chmod: changing permissions of '/config/log/nginx/error.log.1': Bad address
chmod: changing permissions of '/config/log/nginx/error.log.14.gz': Bad address
chmod: changing permissions of '/config/log/nginx/error.log.8.gz': Bad address
chmod: changing permissions of '/config/log/nginx/error.log.9.gz': Bad address
chmod: changing permissions of '/config/log/nginx/error.log.10.gz': Bad address
chmod: changing permissions of '/config/log/nginx/error.log.11.gz': Bad address
chmod: changing permissions of '/config/log/nginx/error.log.12.gz': Bad address
chmod: changing permissions of '/config/log/nginx/error.log.13.gz': Bad address
chmod: changing permissions of '/config/log/php': Bad address
chmod: changing permissions of '/config/log/php/error.log': Bad address
chmod: changing permissions of '/config/log/php/error.log.1': Bad address
chmod: changing permissions of '/config/log/php/error.log.2.gz': Bad address
chmod: changing permissions of '/config/log/php/error.log.3.gz': Bad address
chmod: changing permissions of '/config/log/php/error.log.4.gz': Bad address
chmod: changing permissions of '/config/log/php/error.log.5.gz': Bad address
chmod: changing permissions of '/config/log/php/error.log.6.gz': Bad address
chmod: changing permissions of '/config/log/php/error.log.7.gz': Bad address
chmod: changing permissions of '/config/log/fail2ban': Bad address
chmod: changing permissions of '/config/log/fail2ban/fail2ban.log': Bad address
chmod: changing permissions of '/config/log/fail2ban/fail2ban.log.1': Bad address
chmod: changing permissions of '/config/log/fail2ban/fail2ban.log.2.gz': Bad address
chmod: changing permissions of '/config/log/fail2ban/fail2ban.log.3.gz': Bad address
chmod: changing permissions of '/config/log/fail2ban/fail2ban.log.4.gz': Bad address
chmod: changing permissions of '/config/log/fail2ban/fail2ban.log.5.gz': Bad address
chmod: changing permissions of '/config/log/fail2ban/fail2ban.log.6.gz': Bad address
chmod: changing permissions of '/config/log/fail2ban/fail2ban.log.7.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.2.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.3.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.4.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.5.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.6.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.7.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.8.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.9.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.1': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.10.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.11.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.12.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.13.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.14.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.15.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.16.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.17.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.18.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.19.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.20.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.21.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.22.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.23.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.24.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.25.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.26.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.27.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.28.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.29.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.30.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.31.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.32.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.33.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.34.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.35.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.36.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.37.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.38.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.39.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.40.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.41.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.42.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.43.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.44.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.45.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.46.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.47.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.48.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.49.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.50.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.51.gz': Bad address
chmod: changing permissions of '/config/log/letsencrypt/letsencrypt.log.52.gz': Bad address
chmod: changing permissions of '/config/log/logrotate.status': Bad address
The cert is either expired or it expires within the next day. Attempting to renew. This could take up to 10 minutes.
<------------------------------------------------->

<------------------------------------------------->
`

**Comment by j0nnymoe** [comment]
Why would you use an dev build of swag in place of the mariadb image?

**Comment by salvq** [comment]
Apologies for posting in the wrong section; please disregard this.
