### ISSUE TITLE
Does this image support usage of /docker-entrypoint-initdb.d/?

### ISSUE THREAD

**Issue by Dragas** [linuxserver/docker-mariadb#26]
Hi!

I've found this image as an alternative to regular mariadb images, since my target requires running on ARM architecture, but I've come into an issue that it is not exactly a drop in replacement for original mariadb image. Question stands: Does this image support usage of `/docker-entrypoint-initdb.d/`, where any provided bash and sql scripts would be executed? If not, is there an alternative for such behavior?

References:
https://hub.docker.com/_/mariadb#initializing-a-fresh-instance

**Comment by aptalca** [comment]
No we don't support automatic execution of files in a folder. However, you can put whatever files and scripts into the config folder and run then manually via docker run or exec

**Comment by netwrkx** [comment]
Any update on this feature?

**Comment by CHBMB** [comment]
https://blog.linuxserver.io/2019/09/14/customizing-our-containers/

**Comment by thelamer** [comment]
Just saw this , as this is SQL that needs to be injected post init we should consider adding this
