### ISSUE TITLE
Rebase this image on alpine?

### ISSUE THREAD

**Issue by amyspark** [linuxserver/docker-mariadb#30]
Hey all,

Would it be possible to rebase this image on Alpine, just like [The Lounge](https://github.com/linuxserver/docker-thelounge/blob/ac7253063c1f135e33579694376cdae362757dc7/Dockerfile.armhf#L1) ? I quite like the small size and automated permissions handling of s6 (especially for toying with Docker and volumes).

Thanks in advance!

**Comment by tobbenb** [comment]
S6 have nothing to do with alpine. We use S6 on Ubuntu too.
as for reading, there is most likely a good reason we used Ubuntu when developing the container.
