### ISSUE TITLE
"-" in MYSQL_DATABASE breaks first install

### ISSUE THREAD

**Issue by anoma** [linuxserver/docker-mariadb#31]
The `-` character when used in the MYSQL_DATABASE compose variable breaks first install. Mariadb does not come properly up.

The same compose omitting just the  problem `-` installs correctly.

Manually creating a database with the problem `-` name after first install works correctly.

Using the  `-` in the MYSQL_DATABASE, MYSQL_USER, aliases or container name causes no issues.

I do not know if any other characters cause this issue.

**Comment by tobbenb** [comment]
What do you mean by breaking the install?

**Comment by anoma** [comment]
Install does not complete, remote access does not come up. 

It is enough to replicate. Create a container with something like `MYSQL_DATABASE: bitbit` to confirm it works. Destroy it and try again with `MYSQL_DATABASE: bit-bit`

**Comment by thelamer** [comment]
fixed in latest release
