### ISSUE TITLE
Set root password from file?

### ISSUE THREAD

**Issue by kaysond** [linuxserver/docker-mariadb#35]
Is it possible to set the root password via a file? The official image allows this via the env var `MYSQL_ROOT_PASSWORD_FILE`: https://docs.docker.com/samples/library/mariadb/

This is great for use with docker secrets and would be very helpful for automated deployments

**Comment by kaysond** [comment]
@thelamer so unfortunately your PR didn't quite address this. Using a universal env file with a hard-coded path makes it such that I can't use docker secrets. With docker secrets, the secret file is always located at `/run/secrets`.

So in my PR #36, the idea is to pull the root password from a file location that I can specify

**Comment by thelamer** [comment]
It uses bash , just cat whatever file you want to set it as . 

```
MY_VARIABLE=$(cat /run/secrets/yoursecret)
```

**Comment by kaysond** [comment]
> 
> 
> It uses bash , just cat whatever file you want to set it as .
> 
> ```
> MY_VARIABLE=$(cat /run/secrets/yoursecret)
> ```

Doesn't that sort of pose a security risk? It seems like a bad idea to blindly run bash on a script thats mounted from the outside world. If access to that file is compromised wouldn't it give full access to the container?

I'm really not trying to be difficult or ungrateful, I just don't see the value add in having another way of specifying environment variables when I can just take the same file contents and put it in a `.env` when I run `docker-compose`. 

Having `*_FILE` env var support is a common practice, and addresses an issue that I don't think this extra file does. It's what the official mariadb image does: https://hub.docker.com/_/mariadb?tab=description

**Comment by thelamer** [comment]
You understand that root has access to that file inside the container right ? 
How else are you going to consume the file contents outside of catting it ?

**Comment by thelamer** [comment]
Look I do not want you to think I am being close minded here, I understand your concerns. 

If we can come up with a method of implementing reading env vars from files using strictly ENV variables (so you don't have to bind in a file on initial init) I am game. But it needs to be universal and cover env variables that could be set. Preferably with an array of ENV with corresponding file locations. 

I am looking at writing code once and it covers whenever someone wants to use this with this current container logic and future.

**Comment by kaysond** [comment]
>You understand that root has access to that file inside the container right ?

So if an attacker has root access it doesn't really matter what you do. But suppose an attacker doesn't have root access but is able to gain access to and modify wherever you've mounted `/config/env`. One way is if the permissions are too loose, for example. Now because that file gets run by the container, if the container ever restarts, the attacker would basically have full control. I realize this is a somewhat pathological example, but it's not that far fetched. Docker packages generally get installed with very tight permissions by default (0711 dirs/0600 files). But I can definitely see a user creating a `/var/lib/mariadb` directory and not disabling group access.

Anyways. The main point is I think running bash in a container on an externally mounted file is a bad practice.

> How else are you going to consume the file contents outside of catting it ?

So within the container, you would still have to cat the file contents, yes. But if you're using docker secrets, there's not actually a corresponding file on the host. You would run something like `printf "areallygoodpassword" | docker secret create mysql_root_password -`, and the secret gets put into the swarm's Raft log where its always encrypted. You would then specify the secret in the compose file, and docker creates a "file" at `/run/secrets/mysql_root_password` in the container that has "areallygoodpassword".

As far as actual implementation, this is what the official mariadb image does in their entrypoint script, and I think you could use it or something similar across all LSIO containers:

```
file_env() {
	local var="$1"
	local fileVar="${var}_FILE"
	local def="${2:-}"
	if [ "${!var:-}" ] && [ "${!fileVar:-}" ]; then
		echo >&2 "error: both $var and $fileVar are set (but are exclusive)"
		exit 1
	fi
	local val="$def"
	if [ "${!var:-}" ]; then
		val="${!var}"
	elif [ "${!fileVar:-}" ]; then
		val="$(< "${!fileVar}")"
	fi
	export "$var"="$val"
	unset "$fileVar"
}
```
https://github.com/docker-library/mariadb/blob/a6b2cc14552c8bbe7f29eac780bb709fd4c8804e/docker-entrypoint.sh#L25-L41

In their case, they call `file_env` individually when a particular env var is used, but if you wanted to simplify you could definitely do something like:
```
mysqlvars=(MYSQL_ROOT_PASSWORD MYSQL_DATABASE MYSQL_USER MYSQL_PASSWORD)
for mysqlvar in ${mysqlvars[*]}; do
  file_env $mysqlvar
done
```

**Comment by thelamer** [comment]
The logic only runs once on init so the attacker would have to have the Docker socket or impeccable timing. 

In any case what about a string detection in the variable itself, we could loop through ENV and set vars that have an specific string in them like `.*=LOAD_FROM_FILE:.*` and cat in the file contents for it. 
So you could set like: 
`MYSQL_ROOT_PASSWORD=LOAD_FROM_FILE:/your/path/secret.txt` and the logic would set that env value for consumption on init.

**Comment by kaysond** [comment]
> The logic only runs once on init so the attacker would have to have the Docker socket or impeccable timing.
True, but that happens any time the container is restarted or updated. So if something crashes the container and it restarts, or you're running watchtower to update the container, then as soon as that happens the "payload" gets executed.

> In any case what about a string detection in the variable itself, we could loop through ENV and set vars that have an specific string in them like .*=LOAD_FROM_FILE:.* and cat in the file contents for it.
So you could set like:
MYSQL_ROOT_PASSWORD=LOAD_FROM_FILE:/your/path/secret.txt and the logic would set that env value for consumption on init.

Yeah that would work and achieve the same thing.

The reason I suggested `_FILE` env vars is because 1) it doesn't require any parsing, and 2) that's what everyone else already does, so the behavior is understood and expected. If you use that `file_env` function, it would preserve existing behavior.

Also to make documentation management easier, instead of adding every `_FILE` var, you could just have a section that lists vars that are set-able by file, similar to how docker does theirs.

I'm happy to make a proposal PR for this if you want to see what I'm suggesting. It would basically just be 20 lines at the top of the init script.

**Comment by thelamer** [comment]
I am not talking about in this container , I am talking about baking this into our base image init process. I don't want to PR a bunch of shit across hundreds of repos to support secrets in our images , that is why I was talking about using existing env vars with a specific string we could look for. 
That way on init we should be able to Loop through all env vars and set new ones on match.

**Comment by kaysond** [comment]
>I am not talking about in this container , I am talking about baking this into our base image init process. I don't want to PR a bunch of shit across hundreds of repos to support secrets in our images , that is why I was talking about using existing env vars with a specific string we could look for.
That way on init we should be able to Loop through all env vars and set new ones on match.

Gotcha. You could still do it with something like this:
```shell
for filevar in "$(env | grep _FILE=)"; do
    var=$(echo "$filevar" | awk -F"_FILE=" '{print $1}')
    val=$(< "$(echo "$filevar" | awk -F"_FILE=" '{print $2}')")
    export "$var"="$val";
done
```
maybe ugly but it works :)

**Comment by thelamer** [comment]
For discussion https://github.com/linuxserver/docker-baseimage-alpine/pull/49
