### ISSUE TITLE
ERROR 2002 (HY000): Can't connect to local MySQL server through socket

### ISSUE THREAD

**Issue by netwrkx** [linuxserver/docker-mariadb#37]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior

it supposed to run the script in the custom-cont-init.d folder

SCRIPT dump.sh
`#!/bin/sh

#start dump.sh
mysql -u root -p0000 -e "create database ubox2";
done
#end of dump.sh`

## Current Behavior

`
[custom-init] files found in /config/custom-cont-init.d executing
[custom-init] dump.sh: executing...
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory")
[custom-init] dump.sh: exited 1
`

## Environment
**OS:*RASPBEEY 3B+*      

## Command used to create docker container (run/create/compose/screenshot)

dock-compose build
dock-compose up -d

## Docker logs

`root@DietPi:/home/node_project# docker logs db-mariadb
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    911
User gid:    911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 40-initialise-db: executing...
Setting Up Initial Databases
Installing MariaDB/MySQL system tables in '/config/databases' ...
2019-10-27 13:53:14 1995565888 [Note] /usr/sbin/mysqld (mysqld 10.1.41-MariaDB-0ubuntu0.18.04.1) starting as process 258 ...
OK
Filling help tables...
2019-10-27 13:53:32 1996294976 [Note] /usr/sbin/mysqld (mysqld 10.1.41-MariaDB-0ubuntu0.18.04.1) starting as process 287 ...
OK
Creating OpenGIS required SP-s...
2019-10-27 13:53:35 1995889472 [Note] /usr/sbin/mysqld (mysqld 10.1.41-MariaDB-0ubuntu0.18.04.1) starting as process 317 ...
OK

To start mysqld at boot time you have to copy
support-files/mysql.server to the right place for your system

PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !
To do so, start the server, then issue the following commands:

'/usr/bin/mysqladmin' -u root password 'new-password'
'/usr/bin/mysqladmin' -u root -h efc3dee8e5e3 password 'new-password'

Alternatively you can run:
'/usr/bin/mysql_secure_installation'

which will also give you the option of removing the test
databases and anonymous user created by default.  This is
strongly recommended for production servers.

See the MariaDB Knowledgebase at http://mariadb.com/kb or the
MySQL manual for more instructions.

You can start the MariaDB daemon with:
cd '/usr' ; /usr/bin/mysqld_safe --datadir='/config/databases'

You can test the MariaDB daemon with mysql-test-run.pl
cd '/usr/mysql-test' ; perl mysql-test-run.pl

Please report any problems at http://mariadb.org/jira

The latest information about MariaDB is available at http://mariadb.org/.
You can find additional information about the MySQL part at:
http://dev.mysql.com
Consider joining MariaDB's strong and vibrant community:
https://mariadb.org/get-involved/

2019-10-27 13:53:39 1996319552 [Note] mysqld (mysqld 10.1.41-MariaDB-0ubuntu0.18.04.1) starting as process 345 ...
Database Setup Completed
[cont-init.d] 40-initialise-db: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] files found in /config/custom-cont-init.d executing
[custom-init] dump.sh: executing...
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory")
[custom-init] dump.sh: exited 1
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
191027 13:53:44 mysqld_safe Logging to syslog.
191027 13:53:44 mysqld_safe Starting mysqld daemon with databases from /config/databases
`

**Comment by aptalca** [comment]
Custom init files run after the regular init files, but before the services are started. Mysql is not running while you're script runs.

Either use the built in system to have the container create your database for you via the environment variables, or see the existing init file that creates it and try to mimic it in your custom init.

**Comment by netwrkx** [comment]
here is a snippet of my docker-compse file, database never get created

```
`version: '3'

services:
  mariadb:
    build:
      context: ./db
      dockerfile: mariadb.Dockerfile
    container_name: db-mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      TZ: Europe/London
      MYSQL_USER: root
      MYSQL_DATABASE: ubox2
      MYSQL_PASSWORD: 0000
      MYSQL_ROOT_PASSWORD: 0000
    volumes:
      - ${PWD}
    networks:
      - app-network`

```
mariadb.Dockerfile
```
# ---- Base Node ----
FROM linuxserver/mariadb

```

what to do
