### ISSUE TITLE
Container on armhf won't start (loop) with data processed with amd64 container

### ISSUE THREAD

**Issue by ofthesun9** [linuxserver/docker-mariadb#42]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

I run a cluster with a mixed of amd64 and armhf nodes.
I noticed that once the databases have been processed on a amd64 node, it won't be possible to run them on a armhf node.
I noticed also that the problem is solved if I remove the files : ib_logfile0 ib_logfile1 ibdata1
------------------------------

## Expected Behavior
I would expect that container could be launched on armhf architecture, even if the databases have been used on amd64 architecture.

## Current Behavior
Once the databases have been processed on a amd64 node, it won't be possible to run them on a armhf node.
The container can be started on arm again if the files ib_logfile0, ib_logfile1, ibdata1 are deleted.

## Steps to Reproduce
1. launch a container  on armhf. Wait for proper initialization. Shutdown the container
2. launch a container on amd64 with same /config volume. Wait for start up. Shutdown the container
3. relaunch the container on armhf. The container won't properly start anymore (loop):
mariadb    | 191231 10:19:18 mysqld_safe Logging to syslog.
mariadb    | 191231 10:19:18 mysqld_safe Starting mysqld daemon with databases from /config/databases

## Environment
x86_64 node:
 Container Linux by CoreOS stable (2303.3.0) 
 Docker 18.06.3-ce

arm32 node:
 HypriotOS/armv7  
 Docker 18.06.1-ce

## Command used to create docker container (run/create/compose/screenshot)
version: "2"
services:
  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=xxxx
      - TZ=Europe/London
      - MYSQL_DATABASE=xxxx
      - MYSQL_USER=xxxx
      - MYSQL_PASSWORD=xxxx
    volumes:
      - /mnt/pv/test/config:/config
    ports:
      - 3306:3306
    restart: unless-stopped

## Docker logs
mariadb    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
mariadb    | [s6-init] ensuring user provided files have correct perms...exited 0.
mariadb    | [fix-attrs.d] applying ownership & permissions fixes...
mariadb    | [fix-attrs.d] done.
mariadb    | [cont-init.d] executing container initialization scripts...
mariadb    | [cont-init.d] 01-envfile: executing...
mariadb    | [cont-init.d] 01-envfile: exited 0.
mariadb    | [cont-init.d] 10-adduser: executing...
mariadb    |
mariadb    | -------------------------------------
mariadb    |           _         ()
mariadb    |          | |  ___   _    __
mariadb    |          | | / __| | |  /  \
mariadb    |          | | \__ \ | | | () |
mariadb    |          |_| |___/ |_|  \__/
mariadb    |
mariadb    |
mariadb    | Brought to you by linuxserver.io
mariadb    | We gratefully accept donations at:
mariadb    | https://www.linuxserver.io/donate/
mariadb    | -------------------------------------
mariadb    | GID/UID
mariadb    | -------------------------------------
mariadb    |
mariadb    | User uid:    1000
mariadb    | User gid:    1000
mariadb    | -------------------------------------
mariadb    |
mariadb    | [cont-init.d] 10-adduser: exited 0.
mariadb    | [cont-init.d] 30-config: executing...
mariadb    | [cont-init.d] 30-config: exited 0.
mariadb    | [cont-init.d] 40-initialise-db: executing...
mariadb    | [cont-init.d] 40-initialise-db: exited 0.
mariadb    | [cont-init.d] 99-custom-scripts: executing...
mariadb    | [custom-init] no custom files found exiting...
mariadb    | [cont-init.d] 99-custom-scripts: exited 0.
mariadb    | [cont-init.d] done.
mariadb    | [services.d] starting services
mariadb    | [services.d] done.
mariadb    | 191231 10:16:47 mysqld_safe Logging to syslog.
mariadb    | 191231 10:16:47 mysqld_safe Starting mysqld daemon with databases from /config/databases
mariadb    | 191231 10:16:49 mysqld_safe Logging to syslog.
mariadb    | 191231 10:16:50 mysqld_safe Starting mysqld daemon with dat

**Comment by aptalca** [comment]
Official mariadb repo only provides packages for x86_64 and aarch64. Therefore the arm image here pulls from the ubuntu bionic repo, which is an older version. That's likely the issue. 

I don't recommend moving the mariadb data back and forth between x86_64 and armhf

**Comment by ofthesun9** [comment]
Thanks, it was indeed the issue.
I switched to aarch64 and it is now ok.
I will close the issue.
