### ISSUE TITLE
Warning: World-writable config file '/etc/mysql/conf.d/custom.cnf' is ignored

### ISSUE THREAD

**Issue by GitJamz** [linuxserver/docker-mariadb#43]
I always get this in my log when deploying the container on a synology NAS in docker.
I have gotten this in the past as well. Only information on google is for windows deployments.

**Comment by aptalca** [comment]
The permissions on the file /config/custom.cnf are wrong. Change it to 644 and restart the container

**Comment by GitJamz** [comment]
Ok so for a noob:
I go to the folder where custom.cnf is and write
sudo chmod 644 custom.cnf
Correct? Why is this not in the tutorial/guide for this container?

**Comment by aptalca** [comment]
`Why is this not in the tutorial/guide for this container?`

Because you're the only who had this issue. The permissions by default are correct

**Comment by GitJamz** [comment]
> `Why is this not in the tutorial/guide for this container?`
> 
> Because you're the only who had this issue. The permissions by default are correct

That is impossible.. Its more possible that Im the only one who spotted this in the log and actually cared to write an issue here on github. The container and functions probably work fine without touching this.
But this log entry is for sure present for everyone running this container on a synology NAS and who manually did not set this chmod command on this custom.cnf 
I also saw some people posting about this in the unraid forum also.

**Comment by aptalca** [comment]
1) How do you know it's present for everyone running it on synology? None of the team members have a synology so we have no idea what issues it may have. This container works fine on all the platforms we have tested. I personally use it in production for various company websites.
2) Unraid used to have a script that went through all the appdata folders and chmodded everything to be world writable, hence breaking this. Was fixed on unraid.
3) If you have more information, please submit a proper bug report by filling out the issue template

**Comment by scgf** [comment]
I installed this docker package only yesterday on a Synlogy NAS. I used the alpine version. It shows this error in the logs. I stopped the container and applied chmod 644 custom.cnf, re-started and the error was gone. There is clearly an issue.

**Comment by horrorhound** [comment]
> `Why is this not in the tutorial/guide for this container?`
> 
> Because you're the only who had this issue. The permissions by default are correct

I have this same problem and found this thread...   I'm using Unraid which I think "Fix Permissions" in Unraid is what changes the permissions that ultimately breaks mariadb.

**Comment by aptalca** [comment]
Fix permissions script on unraid is supposed to skip docker data. If yours is not skipping, look into why because it will cause a lot of other issues with various containers.
