### ISSUE TITLE
Expect v10.4 but get v.10.1.44

### ISSUE THREAD

**Issue by natelandau** [linuxserver/docker-mariadb#47]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
Expect to have version 10.4.x installed when pulling the latest tag of the container

## Current Behavior
mariadb runs perfectly, but is the wrong version

`mariadb --version` 
outputs
`mariadb  Ver 15.1 Distrib 10.1.44-MariaDB, for debian-linux-gnueabihf (armv7l) using readline 5.2`

## Steps to Reproduce
Install `linuxserver/mariadb:latest` 

## Environment
**OS:**      Raspbian Buster
**CPU architecture:** arm32     
**How docker service was installed:**      
Using the Nomad Docker driver.  

## Command used to create docker container (run/create/compose/screenshot)
Nomad task template:
```
  task "mariaDB" {
      env {
        PUID = "1000"
        PGID = "1000"
        MYSQL_ROOT_PASSWORD = "[redacted]"
        TZ = "America/New_York"
        MYSQL_USER = "[redacted]"
        MYSQL_PASSWORD = "[redacted]"
      }
      driver = "docker"
      config {
        image = "linuxserver/mariadb:latest"
        hostname = "mariadb"
        volumes = [
          "/mnt/usbDrive/docker/mariaDB:/config"
        ]
        port_map {
          db = 3306
        }
      }
```

## Docker logs
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 40-initialise-db: executing...
[cont-init.d] 40-initialise-db: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
200226 09:45:51 mysqld_safe Logging to syslog.
200226 09:45:51 mysqld_safe Starting mysqld daemon with databases from /config/databases
```

stderr is empty, thankfully.

**Comment by aptalca** [comment]
We pull mariadb from their official repo, but unfortunately they only publish x86_64 and aarch64 packages. So for arm, we pull the bionic repo version, which is a bit behind.

**Comment by geerlingguy** [comment]
I just ran into this issue as well. Unfortunately, Drupal 9.0 does not run on versions older than `10.3.7`, so I can't use this Docker image for ARM 32-bit/v7 builds to run Drupal anymore :(

The `arm64` image has the latest version, so it runs fine.

Over time, this won't be as big a deal, but for now I'm going to have to find a different image that installs the same (later) version of MariaDB on both arches.

**Comment by Dominik-1980** [comment]
> I just ran into this issue as well. Unfortunately, Drupal 9.0 does not run on versions older than `10.3.7`, so I can't use this Docker image for ARM 32-bit/v7 builds to run Drupal anymore :(
> 
> The `arm64` image has the latest version, so it runs fine.
> 
> Over time, this won't be as big a deal, but for now I'm going to have to find a different image that installs the same (later) version of MariaDB on both arches.

Did you find a way?
