### ISSUE TITLE
Bootstrapping of database with .sql files in /config/initdb.d/ not working as intended

### ISSUE THREAD

**Issue by AirPett** [linuxserver/docker-mariadb#48]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
When a `.sql` file is mounted at `/config/initdb.d/` the container should run the SQL-script inside the default database created using the environment variables. This would be consistent with how the official [mariadb](https://hub.docker.com/_/mariadb) container works for `.sql` scripts mounted at `/docker-entrypoint-initdb.d` (please see part "Initializing a fresh instance" in above linked doc).

## Current Behavior
Currently the script `/etc/cont-init.d/40-initialise-db` which creates the SQL init script `/tmp/mysql-first-time.sql` doesn't add a `USE ${MYSQL_DATABASE}` after setting up the initial databases and before adding the init and remote sql scripts. This causes the scripts to fail if they don't contain a `USE` clause at the beginning of them. This is not intended, because the idea of providing the database details with environment variables is to select the database name dynamically and not having to modify the source SQL files based on the value of ENV `MYSQL_DATABASE`.

## Steps to Reproduce
1. Run the container with any database name, username and password, and [gammu.sql](https://gitlab.yobitti.fi/yobitti/gammu-smsd/raw/develop/gammu.sql) mounted at `/config/initdb.d/gammu.sql`.
2. Open a shell to the container
3. Run `mysql -uroot -prootPass`
4. Run `USE abc;` with the abc being the database name you gave it as ENV
5. Run `SHOW TABLES;` and you'll get an empty set.

Everything works if you manually do `mysql -uroot -prootPass abc < /config/initdb.d/gammu.sql`

## Environment
**OS:** Raspbian GNU/Linux 10 (buster) (Linux raspi3-gammu01 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux)
**CPU architecture:** armv7l
**How docker service was installed:** Using the [script](https://docs.docker.com/install/linux/docker-ce/debian/#install-using-the-convenience-script) as instructed by Docker docs.

## Command used to create docker container (run/create/compose/screenshot)
```yaml
version: "3.7"

services:
  gammu-db:
    image: linuxserver/mariadb
    restart: unless-stopped
    env_file:
      - ./gammu-db-config.env
    volumes:
      - gammu-db:/config/databases
      - ./gammu.sql:/config/initdb.d/gammu.sql
    networks:
      - db-gammu

networks:
  db-gammu:

volumes:
  gammu-db:
```

The `./gammu-db-config.env` contents:
```ini
MYSQL_ROOT_PASSWORD=rootPass
TZ=Europe/Helsinki

MYSQL_DATABASE=gammu
MYSQL_USER=gammu
MYSQL_PASSWORD=pass
```

## Docker logs
```
gammu-db_1            | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
gammu-db_1            | [s6-init] ensuring user provided files have correct perms...exited 0.
gammu-db_1            | [fix-attrs.d] applying ownership & permissions fixes...
gammu-db_1            | [fix-attrs.d] done.
gammu-db_1            | [cont-init.d] executing container initialization scripts...
gammu-db_1            | [cont-init.d] 01-envfile: executing...
gammu-db_1            | [cont-init.d] 01-envfile: exited 0.
gammu-db_1            | [cont-init.d] 10-adduser: executing...
gammu-db_1            | usermod: no changes
gammu-db_1            |
gammu-db_1            | -------------------------------------
gammu-db_1            |           _         ()
gammu-db_1            |          | |  ___   _    __
gammu-db_1            |          | | / __| | |  /  \
gammu-db_1            |          | | \__ \ | | | () |
gammu-db_1            |          |_| |___/ |_|  \__/
gammu-db_1            |
gammu-db_1            |
gammu-db_1            | Brought to you by linuxserver.io
gammu-db_1            | We gratefully accept donations at:
gammu-db_1            | https://www.linuxserver.io/donate/
gammu-db_1            | -------------------------------------
gammu-db_1            | GID/UID
gammu-db_1            | -------------------------------------
gammu-db_1            |
gammu-db_1            | User uid:    911
gammu-db_1            | User gid:    911
gammu-db_1            | -------------------------------------
gammu-db_1            |
gammu-db_1            | [cont-init.d] 10-adduser: exited 0.
gammu-db_1            | [cont-init.d] 30-config: executing...
gammu-db_1            | [cont-init.d] 30-config: exited 0.
gammu-db_1            | [cont-init.d] 40-initialise-db: executing...
gammu-db_1            | Setting Up Initial Databases
gammu-db_1            | Installing MariaDB/MySQL system tables in '/config/databases' ...
gammu-db_1            | 2020-03-12 19:31:10 1996028736 [Note] /usr/sbin/mysqld (mysqld 10.1.44-MariaDB-0ubuntu0.18.04.1) starting as process 278 ...
gammu-db_1            | OK
gammu-db_1            | Filling help tables...
gammu-db_1            | 2020-03-12 19:31:43 1996397376 [Note] /usr/sbin/mysqld (mysqld 10.1.44-MariaDB-0ubuntu0.18.04.1) starting as process 307 ...
gammu-db_1            | OK
gammu-db_1            | Creating OpenGIS required SP-s...
gammu-db_1            | 2020-03-12 19:31:47 1995729728 [Note] /usr/sbin/mysqld (mysqld 10.1.44-MariaDB-0ubuntu0.18.04.1) starting as process 337 ...
gammu-db_1            | OK
gammu-db_1            |
gammu-db_1            | To start mysqld at boot time you have to copy
gammu-db_1            | support-files/mysql.server to the right place for your system
gammu-db_1            |
gammu-db_1            | PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !
gammu-db_1            | To do so, start the server, then issue the following commands:
gammu-db_1            |
gammu-db_1            | '/usr/bin/mysqladmin' -u root password 'new-password'
gammu-db_1            | '/usr/bin/mysqladmin' -u root -h d8b04b78a2c2 password 'new-password'
gammu-db_1            |
gammu-db_1            | Alternatively you can run:
gammu-db_1            | '/usr/bin/mysql_secure_installation'
gammu-db_1            |
gammu-db_1            | which will also give you the option of removing the test
gammu-db_1            | databases and anonymous user created by default.  This is
gammu-db_1            | strongly recommended for production servers.
gammu-db_1            |
gammu-db_1            | See the MariaDB Knowledgebase at http://mariadb.com/kb or the
gammu-db_1            | MySQL manual for more instructions.
gammu-db_1            |
gammu-db_1            | You can start the MariaDB daemon with:
gammu-db_1            | cd '/usr' ; /usr/bin/mysqld_safe --datadir='/config/databases'
gammu-db_1            |
gammu-db_1            | You can test the MariaDB daemon with mysql-test-run.pl
gammu-db_1            | cd '/usr/mysql-test' ; perl mysql-test-run.pl
gammu-db_1            |
gammu-db_1            | Please report any problems at http://mariadb.org/jira
gammu-db_1            |
gammu-db_1            | The latest information about MariaDB is available at http://mariadb.org/.
gammu-db_1            | You can find additional information about the MySQL part at:
gammu-db_1            | http://dev.mysql.com
gammu-db_1            | Consider joining MariaDB's strong and vibrant community:
gammu-db_1            | https://mariadb.org/get-involved/
gammu-db_1            |
gammu-db_1            | 2020-03-12 19:31:50 1996397376 [Note] mysqld (mysqld 10.1.44-MariaDB-0ubuntu0.18.04.1) starting as process 365 ...
gammu-db_1            | Database Setup Completed
gammu-db_1            | [cont-init.d] 40-initialise-db: exited 0.
gammu-db_1            | [cont-init.d] 99-custom-scripts: executing...
gammu-db_1            | [custom-init] no custom files found exiting...
gammu-db_1            | [cont-init.d] 99-custom-scripts: exited 0.
gammu-db_1            | [cont-init.d] done.
gammu-db_1            | [services.d] starting services
gammu-db_1            | [services.d] done.
gammu-db_1            | 200312 19:31:56 mysqld_safe Logging to syslog.
gammu-db_1            | 200312 19:31:56 mysqld_safe Starting mysqld daemon with databases from /config/databases
```

I'll create a pull request to be linked with this issue.

**Comment by thelamer** [comment]
Maria does not insert statements they pass the database to the mysql command. 

https://github.com/docker-library/mariadb/blob/master/10.4/docker-entrypoint.sh#L187

We need to think about this , I am not super confident in inserting statements I to user sql and I do not like the official images approach of defining a DB in the MySQL command. 
Need to make sure this cannot break corner case stuff like system commands and stuff. Nothing comes to mind off the top of my head though.

**Comment by AirPett** [comment]
Oh, I see it defines the DB in the command. What I think of this is that it would probably be a pretty rare case to use the env `MYSQL_DATABASE` to create a DB and then not use it. Advanced users probably completely create their databases by themselves and ignore the default environment variables.

I'll submit a pull request that inserts the `USE` statement before the user SQL but feel free to ignore it in case it's inapproppriate. The user can though override it by including a `USE` statement by themselves.

**Comment by thelamer** [comment]
Yeah but you are only thinking about your usecase and not the general universal concept of run all the sql files in this directory or from a remote server. 

I feel like most people are not using this concept in their sql dumps particularly because this has never come up before , we just need to determine if this can harm current deployments by having something like this run before the sql files. 

Again I am worried about running any custom sql on top of users files , need to determine the risks if any and if this is worth it from a potential maintenance standpoint .

**Comment by AirPett** [comment]
I get your point with the general universal use case and maintenance point of view. It's true that often unexpected things happen when something a user didn't ask for is done for them.

However, I see this concept of being able to give databases different names even if they are having the same structure useful with many small services. We for example want to deploy a number of the same container to multiple customers. We want to only maintain a single SQL file for the database structure, but on the other hand we want a different username, password and DB name (for clarity when connecting them to the same phpMyAdmin or other tool instance) for each container and the easiest way is to use the default database and create it with ENVs. This is where the problem comes if we had to add the `USE` into the base SQL file --> we'd end up with one copy of the SQL file for each DB name or some complex script to `sed` the name before mounting the SQL script.
