### ISSUE TITLE
Starting container with empty /config directory does not create required mariadb.sys@localhost user

### ISSUE THREAD

**Issue by JorisMolnar** [linuxserver/docker-mariadb#51]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
When I start the container using an empty /config directory, it creates a fresh `mysql` database. This database contains the user tables and view of MariaDB. 
I expect the user table to contain the default user `mariadb.sys@localhost`.

## Current Behavior
The user tables and view do not contain the user `mariadb.sys@localhost`. This causes MariaDB to throw errors when trying to manage users.

## Steps to Reproduce
Because I am no hero using the MariaDB CLI, these steps and the following docker-compose.yml also contain phpmyadmin. 
1. Make sure the directory `./mariadb/config` is empty, so a new database has to be created.
2. Run `sudo docker-compose up -d` using the docker-compose.yml in this ticket.
3. Go to http://\<hostip\>:8070/
4. Log in using username: `root` and password: `supersecretpass`
5. Click on 'User accounts' in the top navbar.
![image](https://user-images.githubusercontent.com/20184617/82682326-5fb0e780-9c4f-11ea-8f21-98be1848fd22.png)
6. Get error "Not enough privilege to view users."
7. Click in the left sidebar to mysql > Views > user.
![image](https://user-images.githubusercontent.com/20184617/82682555-bb7b7080-9c4f-11ea-9730-a3a0b4fbb8aa.png)
8. Get error "#1449 - The user specified as a definer ('mariadb.sys'@'localhost') does not exist"

## Additional information

Views in MariaDB have a DEFINER user. This user must exist to allow the view to execute. The definer for system view `mysql.user` is `mariadb.sys@localhost`.

If I execute the query that the view normally would execute, I can see there is only one user: `root@%`.

```sql
select `mysql`.`global_priv`.`Host` AS `Host`,`mysql`.`global_priv`.`User` AS `User`,if(json_value(`mysql`.`global_priv`.`Priv`,'$.plugin') in ('mysql_native_password','mysql_old_password'),ifnull(json_value(`mysql`.`global_priv`.`Priv`,'$.authentication_string'),''),'') AS `Password`,if(json_value(`mysql`.`global_priv`.`Priv`,'$.access') & 1,'Y','N') AS `Select_priv`,if(json_value(`mysql`.`global_priv`.`Priv`,'$.access') & 2,'Y','N') AS `Insert_priv`,if(json_value(`mysql`.`global_priv`.`Priv`,'$.access') & 4,'Y','N') AS `Update_priv`,if(json_value(`mysql`.`global_priv`.`Priv`,'$.access') & 8,'Y','N') AS `Delete_priv`,if(json_value(`mysql`.`global_priv`.`Priv`,'$.access') & 16,'Y','N') AS `Create_priv`,if(json_value(`mysql`.`global_priv`.`Priv`,'$.access') & 32,'Y','N') AS `Drop_priv`,if(json_value(`mysql`.`global_priv`.`Priv`,'$.access') & 64,'Y','N') AS `Reload_priv`,if(json_value(`mysql`.`global_priv`.`Priv`,'$.access') & 128,'Y','N') AS `Shutdown_priv`,if(json_value(`mysql`.`global_priv`.`Priv`,'$.access') & 256,'Y','N') AS `Process_priv`,if(json_value(`mysql`.`global_priv`.`Priv`,'$.access') & 512,'Y','N') AS `File_priv`,if(json_value(`mysql`.`global_priv`.`Priv`,'$.access') & 1024,'Y','N') AS `Grant_priv`,if(json_value(`mysql`.`global_priv`.`Priv`,'$.access') & 2048,'Y','N') AS `References_priv`,if(json_value(`mysql`.`global_priv`.`Priv`,'$.access') & 4096,'Y','N') AS `Index_priv`,if(json_value(`mysql`.`global_priv`.`Priv`,'$.access') & 8192,'Y','N') AS `Alter_priv`,if(json_value(`mysql`.`global_priv`.`Priv`,'$.access') & 16384,'Y','N') AS `Show_db_priv`,if(json_value(`mysql`.`global_priv`.`Priv`,'$.access') & 32768,'Y','N') AS `Super_priv`,if(json_value(`mysql`.`global_priv`.`Priv`,'$.access') & 65536,'Y','N') AS `Create_tmp_table_priv`,if(json_value(`mysql`.`global_priv`.`Priv`,'$.access') & 131072,'Y','N') AS `Lock_tables_priv`,if(json_value(`mysql`.`global_priv`.`Priv`,'$.access') & 262144,'Y','N') AS `Execute_priv`,if(json_value(`mysql`.`global_priv`.`Priv`,'$.access') & 524288,'Y','N') AS `Repl_slave_priv`,if(json_value(`mysql`.`global_priv`.`Priv`,'$.access') & 1048576,'Y','N') AS `Repl_client_priv`,if(json_value(`mysql`.`global_priv`.`Priv`,'$.access') & 2097152,'Y','N') AS `Create_view_priv`,if(json_value(`mysql`.`global_priv`.`Priv`,'$.access') & 4194304,'Y','N') AS `Show_view_priv`,if(json_value(`mysql`.`global_priv`.`Priv`,'$.access') & 8388608,'Y','N') AS `Create_routine_priv`,if(json_value(`mysql`.`global_priv`.`Priv`,'$.access') & 16777216,'Y','N') AS `Alter_routine_priv`,if(json_value(`mysql`.`global_priv`.`Priv`,'$.access') & 33554432,'Y','N') AS `Create_user_priv`,if(json_value(`mysql`.`global_priv`.`Priv`,'$.access') & 67108864,'Y','N') AS `Event_priv`,if(json_value(`mysql`.`global_priv`.`Priv`,'$.access') & 134217728,'Y','N') AS `Trigger_priv`,if(json_value(`mysql`.`global_priv`.`Priv`,'$.access') & 268435456,'Y','N') AS `Create_tablespace_priv`,if(json_value(`mysql`.`global_priv`.`Priv`,'$.access') & 536870912,'Y','N') AS `Delete_history_priv`,elt(ifnull(json_value(`mysql`.`global_priv`.`Priv`,'$.ssl_type'),0) + 1,'','ANY','X509','SPECIFIED') AS `ssl_type`,ifnull(json_value(`mysql`.`global_priv`.`Priv`,'$.ssl_cipher'),'') AS `ssl_cipher`,ifnull(json_value(`mysql`.`global_priv`.`Priv`,'$.x509_issuer'),'') AS `x509_issuer`,ifnull(json_value(`mysql`.`global_priv`.`Priv`,'$.x509_subject'),'') AS `x509_subject`,cast(ifnull(json_value(`mysql`.`global_priv`.`Priv`,'$.max_questions'),0) as unsigned) AS `max_questions`,cast(ifnull(json_value(`mysql`.`global_priv`.`Priv`,'$.max_updates'),0) as unsigned) AS `max_updates`,cast(ifnull(json_value(`mysql`.`global_priv`.`Priv`,'$.max_connections'),0) as unsigned) AS `max_connections`,cast(ifnull(json_value(`mysql`.`global_priv`.`Priv`,'$.max_user_connections'),0) as signed) AS `max_user_connections`,ifnull(json_value(`mysql`.`global_priv`.`Priv`,'$.plugin'),'') AS `plugin`,ifnull(json_value(`mysql`.`global_priv`.`Priv`,'$.authentication_string'),'') AS `authentication_string`,'N' AS `password_expired`,elt(ifnull(json_value(`mysql`.`global_priv`.`Priv`,'$.is_role'),0) + 1,'N','Y') AS `is_role`,ifnull(json_value(`mysql`.`global_priv`.`Priv`,'$.default_role'),'') AS `default_role`,cast(ifnull(json_value(`mysql`.`global_priv`.`Priv`,'$.max_statement_time'),0.0) as decimal(12,6)) AS `max_statement_time` from `mysql`.`global_priv`
```
![image](https://user-images.githubusercontent.com/20184617/82684007-3776b800-9c52-11ea-963d-bf954973e965.png)

As a test I have also created a container using the [official mariadb image](https://hub.docker.com/_/mariadb).
When I inspect the user table on this fresh database, I can see it does contain `mariadb.sys@localhost`.
![image](https://user-images.githubusercontent.com/20184617/82684284-9d633f80-9c52-11ea-8804-190d4d8b2671.png)

## Environment
**OS:** Ubuntu Server 20.04 LTS
**CPU architecture:** x86_64
**How docker service was installed:**      
Using APT, following [the official guide on the Docker website](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository)

## Command used to create docker container (run/create/compose/screenshot)
```yaml
version: "3.8"
services:
  mariadb:
    container_name: mariadb
    image: linuxserver/mariadb
    hostname: mariadb
    restart: unless-stopped
    volumes:
      - ./mariadb/config:/config
    environment:
      - MYSQL_ROOT_PASSWORD=supersecretpass
      - PUID=${PUID_MARIADB}
      - PGID
      - TZ

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    init: true
    depends_on:
      - mariadb
    ports:
      - 8070:80
    environment:
      - MYSQL_ROOT_PASSWORD=supersecretpass
      - PMA_HOST=mariadb
```

## Docker logs
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[env-init] MYSQL_ROOT_PASSWORD set from FILE__MYSQL_ROOT_PASSWORD
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    117
User gid:    118
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 40-initialise-db: executing... 
Setting Up Initial Databases
Installing MariaDB/MySQL system tables in '/config/databases' ...
OK

To start mysqld at boot time you have to copy
support-files/mysql.server to the right place for your system


Two all-privilege accounts were created.
One is root@localhost, it has no password, but you need to
be system 'root' user to connect. Use, for example, sudo mysql
The second is abc@localhost, it has no password either, but
you need to be the system 'abc' user to connect.
After connecting you can set the password, if you would need to be
able to connect as any of these users with a password and without sudo

See the MariaDB Knowledgebase at http://mariadb.com/kb or the
MySQL manual for more instructions.

You can start the MariaDB daemon with:
cd '/usr' ; /usr/bin/mysqld_safe --datadir='/config/databases'

You can test the MariaDB daemon with mysql-test-run.pl
cd '/usr/mysql-test' ; perl mysql-test-run.pl

Please report any problems at http://mariadb.org/jira

The latest information about MariaDB is available at http://mariadb.org/.
You can find additional information about the MySQL part at:
http://dev.mysql.com
Consider joining MariaDB's strong and vibrant community:
https://mariadb.org/get-involved/

Database Setup Completed
[cont-init.d] 40-initialise-db: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
200522 14:09:14 mysqld_safe Logging to syslog.
200522 14:09:15 mysqld_safe Starting mysqld daemon with databases from /config/databases
```

**Comment by JorisMolnar** [comment]
As an experiment I did the following steps:

1. Stop both the linuxserver/mariadb and official mariadb containers.
2. Replace /config/databases directory of linuxserver/mariadb with contents of /var/lib/mysql of official image.
3. Change permissions using `chown -R <user>:<group> ./config/databases` to configured user and group of linuxserver/mariadb container.
4. Start linuxserver/mariadb again.

This fixed the error. The `mariadb.sys@localhost` user now exists. But these extra steps are obviously not intended. 😅

**Comment by gabotronix** [comment]
I had the same issue on a Docker Desktop Windows 10 VM. The issue that was reported [here](https://jira.mariadb.org/browse/MDEV-22542) seems to be related.

My workaround was to either use the latest official MariaDB image, or a previous version from LSIO. Both worked out-of-the-box:

- image: mariadb:latest
- image: linuxserver/mariadb:110.4.12mariabionic-ls62

**Comment by drizuid** [comment]
> As an experiment I did the following steps:
> 
> 1. Stop both the linuxserver/mariadb and official mariadb containers.
> 2. Replace /config/databases directory of linuxserver/mariadb with contents of /var/lib/mysql of official image.
> 3. Change permissions using `chown -R <user>:<group> ./config/databases` to configured user and group of linuxserver/mariadb container.
> 4. Start linuxserver/mariadb again.
> 
> This fixed the error. The `mariadb.sys@localhost` user now exists. But these extra steps are obviously not intended. 😅

Amusingly, i just reported this internally to the team before coming to put in my issue. 
To temporarily work around the issue, you can just create the missing user.

```
MariaDB [(none)]> grant all on *.* to 'mariadb.sys'@'localhost' identified by 'MYsql1212';
Query OK, 0 rows affected (0.074 sec)

MariaDB [(none)]> flush privileges;
Query OK, 0 rows affected (0.001 sec)
MariaDB [(none)]> select user,host from mysql.user;
+-------------+-----------+
| User        | Host      |
+-------------+-----------+
| root        | %         |
| mariadb.sys | localhost |
+-------------+-----------+
2 rows in set (0.002 sec)
```

**Comment by drizuid** [comment]
some additional notes guys, this is actually an upstream bug: https://jira.mariadb.org/browse/MDEV-19650. One of our teammembers, saarg, was able to deduce that the last time we weren't affected was ls62 which was on 10.4.12. ls63 was 10.4.13 and seemingly introduced an upstream bug.
