### ISSUE TITLE
Feature request to add the mariabackup package to this container

### ISSUE THREAD

**Issue by Laynezilla** [linuxserver/docker-mariadb#56]
The `mariabackup` package is [included](https://github.com/docker-library/mariadb/blob/master/10.5/Dockerfile#L99) in the official mariadb container. Some people (me) may experience issues when transitioning to this container if they have workflows that use the backup functionality. Plus, it's nice to have an out-of-the-box backup method.

**Comment by drizuid** [comment]
once this PR is accepted, you can simply add
`DOCKER_MODS=linuxserver/mods:mariadb-mariadb-backup`
to your environment variables to get what you're looking for.

**Comment by nemchik** [comment]
This is now built in to the `:alpine` tag, which will soon (ETA March) become the `:latest` tag. I'll close this issue now, but if anyone else comes looking for `mariabackup` please use the `:alpine` tag until the changelog in the readme indicates that we've switched the base to alpine for the `:latest` tag.
