### ISSUE TITLE
Feature Request: add env variable to change mariadb port

### ISSUE THREAD

**Issue by MacGyver27** [linuxserver/docker-mariadb#57]
Hello,

I have couple instances of the mariadb database where they use host IP:

docker-compose.yml:
 ```
network_mode: host
```

I would like to be able to change mariadb port via environment variable rather then editing it in its config file every time:
```
[mysqld]
port                = 33061
```
So it will spin up database directly using e.g. `33061`.

I found something on stackoverflow but it did not work:
```
- MYSQL_TCP_PORT=33061
- MYSQL_UNIX_PORT=33061
```

Thanks, will be appreciated. Michal

**Comment by aptalca** [comment]
Why do they use host networking? I can't think of any reason why you'd need that for mariadb.

**Comment by MacGyver27** [comment]
Simply I want to avoid docker routing and dealing with its iptables rules.. just to have multiple databases on host. I could run them outside the docker, but it is more convenient and faster to use docker-compose.. implementing such a flag to Dockerfile shouldnt be a big deal.. I would appreciate it. Thanks

**Comment by MacGyver27** [comment]
Sounds reasonable?

**Comment by MacGyver27** [comment]
helloooo? no attention ? some statement please

**Comment by j0nnymoe** [comment]
From a personal view, I echo @aptalca's comment and don't see why you aren't just doing `-p 33061:3306` and using that port instead or just having 1 container with all your databases in.

I'll flag this up again with the team and see what the consensus is.

**Comment by drizuid** [comment]
I do not think any of us will spend time adding this support as we all find it superfluous. However, if you'd like to submit a PR, we can take a look for inclusion.
