### ISSUE TITLE
[EDIT] [Feature Request] Write MySQLD console output to file (originally bug report)

### ISSUE THREAD

**Issue by lightlike** [linuxserver/docker-mariadb#58]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
Normal start

## Current Behavior
Infinite startup loop (similar to #42 but on x86_64)

## Steps to Reproduce
1. startup

## Environment
**OS:** OpenMediaVault 5.5.8-1 (SMP Debian 5.7.10-1~bpo10+1 (2020-07-30) x86_64 GNU/Linux)
**CPU architecture:** x86_64
**How docker service was installed:** Single Click via [OMV-Extras](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg)

**Other information:**
- Happened after weekly restart after update between 11.08.2020 and 15.08.2020 (update log below)
- Also happens on fresh installs and on system drive (there are a few problems with docker on Raid-Disks on OMV)
- Docker itsels is located on Raid mount
- Due to a current bug the container cannot do any DNS-Lookups unless the user ID is 1000

## Command used to create docker container (run/create/compose/screenshot)

```
docker create \
  --name=mariadb \
  --net nextcloud-net \
  -e PUID=1007 \
  -e PGID=1001 \
  -e MYSQL_ROOT_PASSWORD=Azk3190 \
  -e TZ=Europe/Berlin \
  -p 3306:3306 \
  -v *appdatapath*/mariaDB:/config \
  --restart unless-stopped \
  linuxserver/mariadb
```

## Docker logs

```
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1007
User gid:    1001
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 40-initialise-db: executing... 
[cont-init.d] 40-initialise-db: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
200826 13:14:51 mysqld_safe Logging to syslog.
200826 13:14:51 mysqld_safe Starting mysqld daemon with databases from /config/databases
200826 13:14:54 mysqld_safe Logging to syslog.
200826 13:14:54 mysqld_safe Starting mysqld daemon with databases from /config/databases
```

Last 2 Lines looping infinetely

## Update Logs

```
Start-Date: 2020-08-14  09:09:00
Commandline: apt-get --yes --allow-downgrades --allow-change-held-packages --fix-broken --fix-missing --auto-remove --allow-unauthenticated --show-upgraded --option DPkg::Options::=--force-confold install linux-image-5.7.0-0.bpo.2-amd64 linux-image-amd64 openmediavault salt-common salt-minion
Install: linux-image-5.7.0-0.bpo.2-amd64:amd64 (5.7.10-1~bpo10+1)
Upgrade: salt-minion:amd64 (3001+ds-1, 3001.1+ds-1), salt-common:amd64 (3001+ds-1, 3001.1+ds-1), linux-image-amd64:amd64 (5.6.14-2~bpo10+1, 5.7.10-1~bpo10+1), openmediavault:amd64 (5.5.6-1, 5.5.7-1)
End-Date: 2020-08-14  09:13:37

Start-Date: 2020-08-15  16:09:19
Commandline: apt-get --yes --allow-downgrades --allow-change-held-packages --fix-broken --fix-missing --auto-remove --allow-unauthenticated --show-upgraded --option DPkg::Options::=--force-confold install openmediavault
Upgrade: openmediavault:amd64 (5.5.7-1, 5.5.8-1)
Remove: linux-image-5.4.0-0.bpo.4-amd64:amd64 (5.4.19-1~bpo10+1)
End-Date: 2020-08-15  16:10:21
```

**Comment by tobbenb** [comment]
So you updated your host and now the mariadb container doesn't work, even when you do a fresh install? That doesn't really sound like a bug in the container, but something in your host have an issue.

**Comment by lightlike** [comment]
I thought so too. But this only happens with linuxserver/mariadb.
I also tried installing the official mariadb docker and that *seemed* to work. (currently trying to move over to that when I got the time.)
I also postet in the OMV-Forums but noone there has any ideas as of this moment.

It would be enough if someone had at least an idea how to fix this.

**Comment by lightlike** [comment]
It seems that the update somehow killed the container and as such it had some transactions that were not closed properly.
This error was shown to me by the console output of the original mariadb docker.

The solution was to start `mysqld` with the argument: `--tc-heuristic-recover=ROLLBACK`

That seemed to fix everything. 

It would have been nice if this docker would have at least wrote the `mysql` console output into a file.
