### ISSUE TITLE
Installation of system tables failed

### ISSUE THREAD

**Issue by billbrod** [linuxserver/docker-mariadb#59]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior

MariaDB docker should start up and initialize the database.

## Current Behavior

mysql is unable to install the system tables, and so I'm unable to connect to the MySQL. Trying the suggestions in the log don't help (running `mysql_install_db --defaults-file=/config/custom.cnf` fails with the same error message and `mysql --skip-grant-tables --general-log` exits with an error).

## Steps to Reproduce

1. startup
2.
3.
4.

## Environment
**OS:** Raspbian GNU/Linux 9
**CPU architecture:** arm32      
**How docker service was installed:** by adding the appropriate lines to a `yml` file for `docker-compose`      

## Command used to create docker container (run/create/compose/screenshot)

`docker-compose -f ~/linuxserver.yml up -d mariadb`

where `linuxserver.yml` contains;

```
services:
  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=rootpass
      - TZ=America/New_York
    volumes:
      - /home/pi/appdata/mariadb:/config
    ports:
      - 3306:3306
    restart: unless-stopped
```

## Docker logs

```
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 40-initialise-db: executing... 
Setting Up Initial Databases
Installing MariaDB/MySQL system tables in '/config/databases' ...
2020-09-10 16:37:49 1996041024 [Note] /usr/sbin/mysqld (mysqld 10.1.44-MariaDB-0ubuntu0.18.04.1) starting as process 285 ...

Installation of system tables failed!  Examine the logs in
/config/databases for more information.

The problem could be conflicting information in an external
my.cnf files. You can ignore these by doing:

    shell> /usr/bin/mysql_install_db --defaults-file=~/.my.cnf

You can also try to start the mysqld daemon with:

    shell> /usr/sbin/mysqld --skip-grant-tables --general-log &

and use the command line tool /usr/bin/mysql
to connect to the mysql database and look at the grant tables:

    shell> /usr/bin/mysql -u root mysql
    mysql> show tables;

Try 'mysqld --help' if you have problems with paths.  Using
--general-log gives you a log in /config/databases that may be helpful.

The latest information about mysql_install_db is available at
https://mariadb.com/kb/en/installing-system-tables-mysql_install_db
You can find the latest source at https://downloads.mariadb.org and
the maria-discuss email list at https://launchpad.net/~maria-discuss

Please check all of the above before submitting a bug report
at http://mariadb.org/jira

2020-09-10 16:37:49 1995574080 [Note] mysqld (mysqld 10.1.44-MariaDB-0ubuntu0.18.04.1) starting as process 288 ...
```

**Comment by billbrod** [comment]
This happens with both the latest image and `arm32v7-110.4.14mariabionic-ls77`

**Comment by aptalca** [comment]
Try it with an empty config folder (or better yet, remove the mountpoint altogether) and see if it starts up

**Comment by billbrod** [comment]
Nope, same error regardless of whether the config folder is populated, empty, or removed.

**Comment by billbrod** [comment]
I was unable to find a solution for this, but I was trying to use this with the LinuxServer Nextcloud image, and I was able to get the official [postgres](https://hub.docker.com/_/postgres/) image working as a backend instead.

**Comment by d-d** [comment]
**A workaround** for this is to create the config directory manually before starting the container
```
mkdir config
chmod 755 config
```

The reported error seems to have a root cause that the /config directory is not created and needs to have write permissions.

The 10-adduser script does chown of directories not yet created until 30-config
40-initialise_db once again does chown -R but not until  the end of the script

The config directory is missing, an error is thrown at docker-compose up, since it's not created until 30-config


When attempting to use `UMASK=0046
`in the docker-compose.yml to get working permissions I discovered a related problem.

The image seems to be forcing UMASK to 0640. I am not sure why this is forced... but it seems wrong, they perhaps intended 640 to be the permissions and not the mask.
```
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
UMASK corrected from 0046 to 0646 ...
201003 12:03:43 mysqld_safe Logging to syslog.
```

The correction logic comes from  /usr/bin/mariadbd-multi 
```
if (defined($ENV{UMASK})) {
  my $UMASK = $ENV{UMASK};
  my $m;
  my $fmode = "0640";

  if(($UMASK =~ m/[^0246]/) || ($UMASK =~ m/^[^0]/) || (length($UMASK) != 4)) {
    printf("UMASK must be a 3-digit mode with an additional leading 0 to indicate octal.\n");
    printf("The first digit will be corrected to 6, the others may be 0, 2, 4, or 6.\n"); }
  else {

```

**Comment by semyonsh** [comment]
This is still an issue on Raspbian 10 and ARMv7 with the latest image.

**Comment by TheSpad** [comment]
> 
> 
> This is still an issue on Raspbian 10 and ARMv7 with the latest image.

I can't replicate this. Raspbian 10 on armv7 (Pi 4b) using the compose from the original post and it starts as expected.

**Comment by semyonsh** [comment]
> 
> 
> > This is still an issue on Raspbian 10 and ARMv7 with the latest image.
> 
> I can't replicate this. Raspbian 10 on armv7 (Pi 4b) using the compose from the original post and it starts as expected.

You're correct, my apologies. 

In all the troubles getting it to work I didn't pay enough attention the most obvious error message:
```

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

Your DockerHost is most likely running an outdated version of libseccomp

To fix this, please visit https://docs.linuxserver.io/faq#libseccomp

Some apps might not behave correctly without this

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

```

Followed the instructions at mentioned link and updated libseccomp:
```
wget http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.1-1_armhf.deb
dpkg -i libseccomp2_2.5.1-1_armhf.deb
```
Hope this helps anyone who also doesn't read properly :)

**Comment by stoinov** [comment]
I have the same issue with using latest `linux/arm64/v8` image on Odroid-C2 using [DietPi](https://dietpi.com/) (optimized Debian) as OS.
I don't see the `libseccomp` error in my logs - just the same thing as in the initial post.

I created the config folder, and put the `env` file inside. Once ran the container created `databases` and `logs` folder and initializes the `custom.cnf` file. but fails on the next steps.

**Comment by TheSpad** [comment]
> 
> 
> I have the same issue with using latest `linux/arm64/v8` image on Odroid-C2 using [DietPi](https://dietpi.com/) (optimized Debian) as OS. I don't see the `libseccomp` error in my logs - just the same thing as in the initial post.
> 
> I created the config folder, and put the `env` file inside. Once ran the container created `databases` and `logs` folder and initializes the `custom.cnf` file. but fails on the next steps.

What version of docker are you running?

**Comment by TheSpad** [comment]
Oh, made a typo, should be
```
docker exec mariadb scmp_sys_resolver faccessat2
```

**Comment by stoinov** [comment]
running the container with: `docker run -d --restart unless-stopped --network test --name mariadb -h mariadb -e TZ=Europe/Sofia -e PUID=0 -e PGID=0 -v /mariadb:/config linuxserver/mariadb`
the config folder holds an `env` file with the required properties.
<details><summary>here are the logs:</summary>

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    0
User gid:    0
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 40-initialise-db: executing... 
Setting Up Initial Databases
Installing MariaDB/MySQL system tables in '/config/databases' ...
Illegal instruction (core dumped)
Installation of system tables failed!  Examine the logs in
/config/databases for more information.
The problem could be conflicting information in an external
my.cnf files. You can ignore these by doing:
    shell> /usr/bin/mysql_install_db --defaults-file=~/.my.cnf
You can also try to start the mysqld daemon with:
    shell> /usr/bin/mysqld --skip-grant-tables --general-log &
and use the command line tool /usr/bin/mysql
to connect to the mysql database and look at the grant tables:
    shell> /usr/bin/mysql -u root mysql
    mysql> show tables;
Try 'mysqld --help' if you have problems with paths.  Using
--general-log gives you a log in /config/databases that may be helpful.
The latest information about mysql_install_db is available at
https://mariadb.com/kb/en/installing-system-tables-mysql_install_db
You can find the latest source at https://downloads.mariadb.org and
the maria-discuss email list at https://launchpad.net/~maria-discuss
Please check all of the above before submitting a bug report
at https://mariadb.org/jira
/var/run/s6/etc/cont-init.d/40-initialise-db: line 4:   294 Illegal instruction     (core dumped) mysqld --datadir="${DATADIR}" --init-file="${tempSqlFile}" --user=abc
```
</details>

**Comment by stoinov** [comment]
from the upstream issue it seems that the last usable version for arm64 seems to be 10.4.13. Confirming that tag `110.4.13mariabionic-ls76` works on my device.
We will be waiting for a permanent resolution by the MariaDB team.
