### ISSUE TITLE
Docker image ghcr.io/linuxserver/mariadb:110.4.15mariabionic-ls86 for linux/arm provide Ver 10.1.47-MariaDB-0ubuntu0.18.04.1

### ISSUE THREAD

**Issue by ptisserand** [linuxserver/docker-mariadb#62]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

While trying docker image ghcr.io/linuxserver/mariadb:110.4.15mariabionic-ls86 on raspbian, I have found that mariadb server is not the correct one.

------------------------------

## Expected Behavior

mariadb version should be "mysqld  Ver 10.4.15-MariaDB-1:10.4.15+maria~bionic-log" as in amd64 docker image

## Current Behavior

mariadb version is "mysqld  Ver 10.1.47-MariaDB-0ubuntu0.18.04.1mysqld  Ver 10.1.47-MariaDB-0ubuntu0.18.04.1"

## Steps to Reproduce

1. docker pull ghcr.io/linuxserver/mariadb:110.4.15mariabionic-ls86
2. docker run --rm -t -i ghcr.io/linuxserver/mariadb:110.4.15mariabionic-ls86 mysqld --version
3.
4.

## Environment
**OS:** raspbian
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

From the official docker repo

## Image information:
        "Id": "sha256:04708e886d7f27c62fcabb490cdf18e9a13f7e457b03957350311b3e0ddfb721",
        "RepoTags": [
            "linuxserver/mariadb:latest",
            "ghcr.io/linuxserver/mariadb:110.4.15mariabionic-ls86",
            "ghcr.io/linuxserver/mariadb:latest"
        ],
        "RepoDigests": [
            "linuxserver/mariadb@sha256:804dadb1be8cf274df045f5ca0df64001f6687dbb028275ee9a886eb50ff5f86",
            "ghcr.io/linuxserver/mariadb@sha256:804dadb1be8cf274df045f5ca0df64001f6687dbb028275ee9a886eb50ff5f86"
        ],

## Extra information:
I have check if it was an issue with outdated package, and it seems that this issue is related to the following warning/error:
```
N: Skipping acquire of configured file 'main/binary-armhf/Packages' as repository 'http://mirror.rackspace.com/mariadb/repo/10.4/ubuntu bionic InRelease' doesn't support architecture 'armhf'N: Skipping acquire of configured file 'main/binary-armhf/Packages' as repository 'http://mirror.rackspace.com/mariadb/repo/10.4/ubuntu bionic InRelease' doesn't support architecture 'armhf'
```

**Comment by aptalca** [comment]
See here #47
