### ISSUE TITLE
How do I update to 10.4?

### ISSUE THREAD

**Issue by ei23-fxg** [linuxserver/docker-mariadb#68]
---
name: update to 10.4 on ARMv7 (32Bit)

---
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

Update MariaDB for 32Bit Arm to 10.2 or higher

## Current Behavior

my MariaDB says it has "Server version: 10.1.47-MariaDB-0ubuntu0.18.04.1 Ubuntu 18.04"
when logging in with `docker exec -it mariadb mysql -p nextcloud`
`docker inspect -f '{{ index .Config.Labels "build_version" }}' mariadb` 
says
Linuxserver.io version:- 110.4.17mariabionic-ls7 Build-date:- 2021-01-16T06:29:38+00:00

**Comment by tobbenb** [comment]
It would be nice if you followed the template for issues.

You are probably running arm 32bit hardware/OS and there is no newer build for that arch.

**Comment by ei23-fxg** [comment]
> 
> 
> It would be nice if you followed the template for issues.
> 
> You are probably running arm 32bit hardware/OS and there is no newer build for that arch.

Yes, i'm on a Raspberry Pi 4
I adjusted the issue to the template... Kind of.

**Comment by tobbenb** [comment]
As I already said, there are no newer release for 32bit. So we can't do much about it.
