### ISSUE TITLE
Why not update MariaDB armhf image to 10.3.27?

### ISSUE THREAD

**Issue by SignumPL** [linuxserver/docker-mariadb#70]
I know there are multiple closed issues about that #68 #62 #60 #47 and #45
**But** - actually there is mariadb armhf build available in version 10.3. When I install it from official Raspbian Buster repository, I get mariadb server 10.3.27. So what's the actual problem? Why we can't update mariadb linuxserver armhf image to 10.3?

The reason why I'm asking is that I'm using Nextcloud and they stop support mariadb 10.1 very soon.

**Comment by tobbenb** [comment]
We just closed another one and you manage to open a new issue. We don't use Debian, but Ubuntu as the base OS.

**Comment by Bolkarr** [comment]
> 
> 
> I know there are multiple closed issues about that #68 #62 #60 #47 and #45
> **But** - actually there is mariadb armhf build available in version 10.3. When I install it from official Raspbian Buster repository, I get mariadb server 10.3.27. So what's the actual problem? Why we can't update mariadb linuxserver armhf image to 10.3?
> 
> The reason why I'm asking is that I'm using Nextcloud and they stop support mariadb 10.1 very soon.

Hi SignumPL, did you find a solution? Can we create a new docker from the official Raspbian Buster repository?

**Comment by Roxedus** [comment]
> did you find a solution?

#66 should help
