### ISSUE TITLE
alpine does not initialize with the correct date resulting in an error

### ISSUE THREAD

**Issue by stonics** [linuxserver/docker-mariadb#78]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

I would expect it to initialize correctly.

## Current Behavior

It initializes fine when I create a container using the latest tag. I'm using this container as a db for nextcloud which complains about using an older version. Therefore I tried to switch to the alpine tag and got the error.
It fails with the error `286213-04-14 10:25:39 0 [ERROR] This MySQL server doesn't support dates later than 2038` during startup

## Steps to Reproduce

1. initialize using the image linuxserver/mariadb:alpine
2. 
3.
4.

## Environment
**OS:** Raspbian buster (Debian 10.8) with Linux kernel 5.10.11-v7l+ 
**CPU architecture:** arm32 (raspberry pi 4)
**How docker service was installed:** Create a stack using portainer with a docker-compose yaml script

## Command used to create docker container (run/create/compose/screenshot)

I create a new portainer stack using this docker-compose yaml script:

version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: ghcr.io/linuxserver/mariadb:alpine
    restart: always
    volumes:
       - /opt/appdata/mariadb:/config
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass
      - MYSQL_PASSWORD=db_pass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - PGID=1001
      - PUID=1001
      - TZ=America/Chicago

  app:
    image: nextcloud
    restart: always
    ports:
      - 18080:80
    links:
      - db
    volumes:
      - /mnt/easystore/nextcloud:/var/www/html/data
      - /opt/appdata/nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=db_pass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db:3306
      - PGID=1001
      - PUID=1001
      - TZ=America/Chicago

## Docker logs

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 01-envfile: executing... ,
[cont-init.d] 01-envfile: exited 0.,
[cont-init.d] 10-adduser: executing... ,
,
-------------------------------------,
          _         (),
         | |  ___   _    __,
         | | / __| | |  /  \ ,
         | | \__ \ | | | () |,
         |_| |___/ |_|  \__/,
,
,
Brought to you by linuxserver.io,
-------------------------------------,
,
To support LSIO projects visit:,
https://www.linuxserver.io/donate/,
-------------------------------------,
GID/UID,
-------------------------------------,
,
User uid:    1001,
User gid:    1001,
-------------------------------------,
,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 30-config: executing... ,
[cont-init.d] 30-config: exited 0.,
[cont-init.d] 40-initialise-db: executing... ,
Setting Up Initial Databases,
Installing MariaDB/MySQL system tables in '/config/databases' ...,
286213-04-14 10:25:39 0 [ERROR] This MySQL server doesn't support dates later than 2038,
,
Installation of system tables failed!  Examine the logs in,
/config/databases for more information.,
,
The problem could be conflicting information in an external,
my.cnf files. You can ignore these by doing:,
,
    shell> /usr/bin/mysql_install_db --defaults-file=~/.my.cnf,
,
You can also try to start the mysqld daemon with:,
,
    shell> /usr/bin/mysqld --skip-grant-tables --general-log &,
,
and use the command line tool /usr/bin/mysql,
to connect to the mysql database and look at the grant tables:,
,
    shell> /usr/bin/mysql -u root mysql,
    mysql> show tables;,
,
Try 'mysqld --help' if you have problems with paths.  Using,
--general-log gives you a log in /config/databases that may be helpful.,
,
The latest information about mysql_install_db is available at,
https://mariadb.com/kb/en/installing-system-tables-mysql_install_db,
You can find the latest source at https://downloads.mariadb.org and,
the maria-discuss email list at https://launchpad.net/~maria-discuss,
,
Please check all of the above before submitting a bug report,
at https://mariadb.org/jira,
,
437489-07-07 13:35:04 0 [ERROR] This MySQL server doesn't support dates later than 2038,

I can see that the date is set incorrectly in the container:

Wed Dec 31 18:00:00 CST 1969

**Comment by Roxedus** [comment]
You are running into [this](https://docs.linuxserver.io/faq#libseccomp). I did not account for timezones when I created the warning you would have seen.

**Comment by stonics** [comment]
Thank you, I did not check the FAQ. I updated libseccomp2 using buster backports as suggested and it is working now.
