### ISSUE TITLE
Internal port different from 3306 

### ISSUE THREAD

**Issue by RiccardoRomagnoli** [linuxserver/docker-mariadb#79]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

By setting ports:  3307:3307 I expect the db to be internally accessible in 3307
I even tried to set the env MYSQL_TCP_PORT to 3307, without success

## Current Behavior

The db container is still only accessible at port 3306

## Steps to Reproduce

1. Set internal port to 3307
2. Try to access the db from another container using port 3307
3. In docker-compose have two containers with image: ghcr.io/linuxserver/mariadb, the first one with port 3306 the second with port 3307

## Environment
**OS:** any
**CPU architecture:** x86_64/arm32/arm64

**Comment by tobbenb** [comment]
You don't change the internal port, only the host port.

**Comment by RiccardoRomagnoli** [comment]
Ok, so better to specify that in the doc :)

**Comment by tobbenb** [comment]
That is basic principles of docker and is explained in the parameters section in the readme.

**Comment by RiccardoRomagnoli** [comment]
As mentioned:

> Container images are configured using parameters passed at runtime (such as those above). These parameters are separated by a colon and indicate <external>:<internal> respectively. For example, -p 8080:80 would expose port 80 from inside the container to be accessible from the host's IP on port 8080 outside the container.

I would say that there could be specified that the internal port cant be different than 3306

**Comment by aptalca** [comment]
As the readme says, if you want to make 3307 accessible from the outside, you'd do what you did. The problem is, nothing is listening on port 3307. Mapping is just that, it has nothing to do with what ports the services are listening on inside.
