### ISSUE TITLE
Fails to install on WD EX4100 NAS - Segmentation Fault

### ISSUE THREAD

**Issue by EventuallyFixed** [linuxserver/docker-mariadb#86]
**The NAS**
The NAS has a [Marvell Armada 388](https://www.verical.com/datasheet/marvell-technology-group-application-processors-and-soc-88f6820-b0-brt4i133-6589795.pdf) processor, which is a dual core based on the Arm v7 design.

It is running OS5, with the latest patch, and has [Docker v19.03.13](https://bintray.com/beta/#/tfl/wdpksrc/Docker/19.03.13?tab=files), as found here, installed.

**The plan**
Trying to get a dockerised NextCloud installed, I planned for
- The official NextCloud image
- This MariaDB image
- Redis official image
- Reverse Proxy (httpd)
- Let's encrypt (lsioarmhf/letsencrypt)

**The Work Around**
- When Mariadb did not work, I tried the latest official Postgres image, which I had no issues with.

**Percieved problem with this image**
Running the image results in a Segmentation Fault at the stage of, "Installing MariaDB/MySQL system tables in '/config/databases' "

Runtime Log
> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
> [s6-init] ensuring user provided files have correct perms...exited 0.,
> [fix-attrs.d] applying ownership & permissions fixes...,
> [fix-attrs.d] done.,
> [cont-init.d] executing container initialization scripts...,
> [cont-init.d] 01-envfile: executing... ,
> [cont-init.d] 01-envfile: exited 0.,
> [cont-init.d] 10-adduser: executing... ,
> usermod: no changes,
> ,
> -------------------------------------,
>           _         (),
>          | |  ___   _    __,
>          | | / __| | |  /  \ ,
>          | | \__ \ | | | () |,
>          |_| |___/ |_|  \__/,
> ,
> ,
> Brought to you by linuxserver.io,
> -------------------------------------,
> ,
> To support LSIO projects visit:,
> https://www.linuxserver.io/donate/,
> -------------------------------------,
> GID/UID,
> -------------------------------------,
> ,
> User uid:    911,
> User gid:    911,
> -------------------------------------,
> ,
> [cont-init.d] 10-adduser: exited 0.,
> [cont-init.d] 30-config: executing... ,
> [cont-init.d] 30-config: exited 0.,
> [cont-init.d] 40-initialise-db: executing... ,
> Setting Up Initial Databases,
> Installing MariaDB/MySQL system tables in '/config/databases' ...,
**> Segmentation fault,
> ,
> Installation of system tables failed!  Examine the logs in,
> /config/databases for more information.,**
> ,
> The problem could be conflicting information in an external,
> my.cnf files. You can ignore these by doing:,
> ,
>     shell> /usr/bin/mysql_install_db --defaults-file=~/.my.cnf,
> ,
> You can also try to start the mysqld daemon with:,
> ,
>     shell> /usr/sbin/mysqld --skip-grant-tables --general-log &,
> ,
> and use the command line tool /usr/bin/mysql,
> to connect to the mysql database and look at the grant tables:,
> ,
>     shell> /usr/bin/mysql -u root mysql,
>     mysql> show tables;,
> ,
> Try 'mysqld --help' if you have problems with paths.  Using,
> --general-log gives you a log in /config/databases that may be helpful.,
> ,
> The latest information about mysql_install_db is available at,
> https://mariadb.com/kb/en/installing-system-tables-mysql_install_db,
> You can find the latest source at https://downloads.mariadb.org and,
> the maria-discuss email list at https://launchpad.net/~maria-discuss,
> ,
> Please check all of the above before submitting a bug report,
> at http://mariadb.org/jira,
> ,
> 2021-06-21 14:23:25 3068126416 [Note] mysqld (mysqld 10.1.48-MariaDB-0ubuntu0.18.04.1) starting as process 297 ...,

**To Reproduce**
- Create a clean folder in /shares/docker/mariadb
- Run the image with the following:
> docker run -d \
>   --name=mariadb \
>   --security-opt seccomp=unconfined \
>   -e PUID=1000 \
>   -e PGID=1000 \
>   -e MYSQL_ROOT_PASSWORD=mariadb \
>   -e TZ=Europe/London \
>   -p 3307:3306 \
>   -v /shares/docker/mariadb:/config \
>   --restart unless-stopped \
>   linuxserver/mariadb

(--security-opt seccomp=unconfined must be stated here, as a workaround)

**Try to connect**
root@be552b771326:/config/databases# /usr/bin/mysql -u root mysql
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory")

**General Log**
root@be552b771326:/config/databases# mysqld --general-log
2021-06-24 19:41:12 3063375056 [Note] mysqld (mysqld 10.1.48-MariaDB-0ubuntu0.18.04.1) starting as process 536 ...
Segmentation fault

**Comment by tobbenb** [comment]
Have you tried specifying the armv7 tag and see if that works? Might be that the NAS is using the x86 image for some reason.
Also your PUID and PGID are not set as they say 911 and not 1000

**Comment by EventuallyFixed** [comment]
Thanks for your really quick response, and your suggestions.

On [hub.docker.com](https://hub.docker.com/r/linuxserver/mariadb) an example specifies PUID=1000 & PGID=1000.  I've tried various combinations of these, such as the values of the NAS superuser, and also matching the UID and GID of the config folder on the file system, as per the instructions there.  I referred to /etc/passwd & /etc/group to find the IDs.

I also tried to pull the specific tag, using the following command, but with the same result as above.

> docker run -d \
>   --name=mariadb \
>   --security-opt seccomp=unconfined \
>   -e PUID=1000 \
>   -e PGID=1000 \
>   -e MYSQL_ROOT_PASSWORD=mariadb \
>   -e TZ=Europe/London \
>   -p 3307:3306 \
>   -v /shares/docker/mariadb:/config \
>   --restart unless-stopped \
>   linuxserver/mariadb:arm32v7-latest

Unable to find image 'linuxserver/mariadb:arm32v7-latest' locally
arm32v7-latest: Pulling from linuxserver/mariadb
d09fb612db8b: Pull complete
a12f014834a9: Pull complete
afcbe4bba7c6: Pull complete
e4ef9aacf28a: Pull complete
48667e7882d9: Pull complete
450bb7f3b58b: Pull complete
4f6e5987139e: Pull complete
d347b2c58319: Pull complete
648d2398540b: Pull complete
Digest: sha256:17a21cea8a6109f743affa6480ee36d62f5bd2f684c3d01f036a9ce730349c23
Status: Downloaded newer image for linuxserver/mariadb:arm32v7-latest
96389-snip-cc85

**Comment by EventuallyFixed** [comment]
Aha!  I pulled the Alpine version and, whaddayaknow!  It works!

**Command**
> docker run -d \
>   --name=mariadb \
>   --security-opt seccomp=unconfined \
>   -e PUID=1000 \
>   -e PGID=1000 \
>   -e MYSQL_ROOT_PASSWORD=mariadb \
>   -e TZ=Europe/London \
>   -p 3307:3306 \
>   -v /shares/docker/mariadb:/config \
>   --restart unless-stopped \
>   **ghcr.io/linuxserver/mariadb:alpine**

  
**Log**

>   https://hub.docker.com/r/linuxserver/mariadb
>   
> -------------------------------------,
> ,
> To support LSIO projects visit:,
> https://www.linuxserver.io/donate/,
> -------------------------------------,
> GID/UID,
> -------------------------------------,
> ,
> User uid:    1002,
> User gid:    1000,
> -------------------------------------,
> ,
> [cont-init.d] 10-adduser: exited 0.,
> [cont-init.d] 30-config: executing... ,
> [cont-init.d] 30-config: exited 0.,
> [cont-init.d] 40-initialise-db: executing... ,
> Setting Up Initial Databases,
> Installing MariaDB/MySQL system tables in '/config/databases' ...,
> 2021-06-24 21:13:19 1 [Warning] Failed to load slave replication state from table mysql.gtid_slave_pos: 1017: Can't find file: './mysql/' (errno: 2 "No such file or directory"),
> OK,
> ,
> To start mysqld at boot time you have to copy,
> support-files/mysql.server to the right place for your system,
> ,
> ,
> PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !,
> To do so, start the server, then issue the following commands:,
> ,
> '/usr/bin/mysqladmin' -u root password 'new-password',
> '/usr/bin/mysqladmin' -u root -h 7f8893dbe9c5 password 'new-password',
> ,
> ternatively you can run:,
> '/usr/bin/mysql_secure_installation',
> ,
> which will also give you the option of removing the test,
> databases and anonymous user created by default.  This is,
> strongly recommended for production servers.,
> ,
> See the MariaDB Knowledgebase at https://mariadb.com/kb or the,
> MySQL manual for more instructions.,
> ,
> You can start the MariaDB daemon with:,
> cd '/usr' ; /usr/bin/mysqld_safe --datadir='/config/databases',
> ,
> You can test the MariaDB daemon with mysql-test-run.pl,
> cd '/usr/mysql-test' ; perl mysql-test-run.pl,
> ,
> Please report any problems at https://mariadb.org/jira,
> ,
> The latest information about MariaDB is available at https://mariadb.org/.,
> You can find additional information about the MySQL part at:,
> https://dev.mysql.com,
> Consider joining MariaDB's strong and vibrant community:,
> https://mariadb.org/get-involved/,
> ,
> 2021-06-24 21:13:21 0 [Note] mysqld (mysqld 10.5.11-MariaDB-log) starting as process 303 ...,
> 2021-06-24 21:13:21 0 [Warning] Could not increase number of max_open_files to more than 1024 (request: 6533),
> 2021-06-24 21:13:21 0 [Note] InnoDB: Uses event mutexes,
> 2021-06-24 21:13:21 0 [Note] InnoDB: Compressed tables use zlib 1.2.11,
> 2021-06-24 21:13:21 0 [Note] InnoDB: Number of pools: 1,
> 2021-06-24 21:13:21 0 [Note] InnoDB: Using generic crc32 instructions,
> 2021-06-24 21:13:21 0 [Note] mysqld: O_TMPFILE is not supported on /var/tmp (disabling future attempts),
> 2021-06-24 21:13:21 0 [Note] InnoDB: Using Linux native AIO,
> 2021-06-24 21:13:21 0 [Note] InnoDB: Initializing buffer pool, total size = 268435456, chunk size = 134217728,
> 2021-06-24 21:13:21 0 [Note] InnoDB: Completed initialization of buffer pool,
> 2021-06-24 21:13:21 0 [Note] InnoDB: 128 rollback segments are active.,
> 2021-06-24 21:13:21 0 [Note] InnoDB: Creating shared tablespace for temporary tables,
> 2021-06-24 21:13:21 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...,
> 2021-06-24 21:13:21 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.,
> 2021-06-24 21:13:21 0 [Note] InnoDB: 10.5.11 started; log sequence number 45106; transaction id 20,
> 2021-06-24 21:13:21 0 [Note] Plugin 'FEEDBACK' is disabled.,
> 2021-06-24 21:13:21 0 [Note] InnoDB: Loading buffer pool(s) from /config/databases/ib_buffer_pool,
> 2021-06-24 21:13:21 0 [Note] Server socket created on IP: '::'.,
> 2021-06-24 21:13:21 0 [Note] InnoDB: Buffer pool(s) load completed at 210624 21:13:21,
> 2021-06-24 21:13:21 0 [Note] Reading of all Master_info entries succeeded,
> 2021-06-24 21:13:21 0 [Note] Added new Master_info '' to hash table,
> 2021-06-24 21:13:21 0 [Note] mysqld: ready for connections.,
> Version: '10.5.11-MariaDB-log'  socket: '/run/mysqld/mysqld.sock'  port: 3306  MariaDB Server,
> 2021-06-24 21:13:23 0 [Note] mysqld (initiated by: root[root] @ localhost []): Normal shutdown,
> 2021-06-24 21:13:23 0 [Note] Event Scheduler: Purging the queue. 0 events,
> 2021-06-24 21:13:23 0 [Note] InnoDB: FTS optimize thread exiting.,
> 2021-06-24 21:13:23 0 [Note] InnoDB: Starting shutdown...,
> 2021-06-24 21:13:23 0 [Note] InnoDB: Dumping buffer pool(s) to /config/databases/ib_buffer_pool,
> 2021-06-24 21:13:23 0 [Note] InnoDB: Buffer pool(s) dump completed at 210624 21:13:23,
> 2021-06-24 21:13:23 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1",
> 2021-06-24 21:13:23 0 [Note] InnoDB: Shutdown completed; log sequence number 45118; transaction id 23,
> 2021-06-24 21:13:23 0 [Note] mysqld: Shutdown complete,
> ,
> Database Setup Completed,
> [cont-init.d] 40-initialise-db: exited 0.,
> [cont-init.d] 90-custom-folders: executing... ,
> [cont-init.d] 90-custom-folders: exited 0.,
> [cont-init.d] 99-custom-files: executing... ,
> [custom-init] no custom files found exiting...,
> [cont-init.d] 99-custom-files: exited 0.,
> [cont-init.d] done.,
> [services.d] starting services,
> [services.d] done.,
> 210624 21:13:24 mysqld_safe Logging to '/config/databases/7f8893dbe9c5.err'.,
> 210624 21:13:24 mysqld_safe Starting mariadbd daemon with databases from /config/databases,
