### ISSUE TITLE
Feature request to add automatic backups

### ISSUE THREAD

**Issue by NaruZosa** [linuxserver/docker-mariadb#98]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
Automatic scheduled backups (daily or weekly) to restore from in the event of database corruption
Even one backup would be beneficial, as it would be something an external backup tool can make a copy of to restore if needed, unlike an in use database.

## Current Behavior
No automatic backups, with no guide on setting this up

## Alternatives Considered
Using backup tools, but these don't back up databases properly, and in the case of MariaDB result in unusable backups.
Using a backup script, but for something this critical, it would benefit the whole userbase to have it as default functionality.

**Comment by BradleyDS2** [comment]
Would still be good to see

**Comment by BradleyDS2** [comment]
Not stale

**Comment by BradleyDS2** [comment]
Not stale

**Comment by BradleyDS2** [comment]
Not stale

**Comment by kaysond** [comment]
@BradleyDS2 I've been using the `cron` mod to do this by running a nightly script:

```
#!/usr/bin/with-contenv bash
mysqldump -h localhost --user=root --password="xxxxxxxxxxxxxxxxxxxxxxxxx" --all-databases | \
    gzip -c > /config/backups/backup_"$(date +%Y-%m-%d_%H:%M:%S)".sql.gz

# keep last 7
ls -t /config/backups/backup_*.sql.gz | \
    tail -n +8 | \
    xargs -r rm
```

You might also be interested in https://github.com/RealOrangeOne/docker-db-auto-backup although I wasn't a fan of giving a backup container access to the docker socket, and I was too lazy to add a proxy.

Agree that this would be a nice built-in feature!

**Comment by BradleyDS2** [comment]
Losing faith in LS when nobody on the team has even commented and the issue keeps being marked as stale.

Not stale.

**Comment by Roxedus** [comment]
Lack of response is due to everyone on the team already handling sql dumps, or just whole appdata backups seperatly. thus not having the motivation to develop this.

**Comment by BradleyDS2** [comment]
Is it possible to mark this issue as not stale so that it's not marked as stale every month?

**Comment by JTBrinkmann** [comment]
That's against the whole point of marking issues as stale. The bot is **correctly** marking it as stale, because it **is** stale.

**Comment by BradleyDS2** [comment]
This feature request won't stop being wanted suddenly due to a version update.

I thought the point of having issues marked as stale was because they are no longer relevant, which is why stale issues are autoclosed.
My apologies for misunderstanding.

**Comment by kaysond** [comment]
@Roxedus would you take a PR to add this? Any thoughts on implementation? Add the cron pkg and a service script that only runs if you turn it on?

**Comment by kaysond** [comment]
not stale

**Comment by drizuid** [comment]
In case it wasn't clear, none of us have any interest in adding this feature.  You are all more than welcome to create a docker mod to add some functionality for this if you like, but we will not be doing it.

**Comment by NaruZosa** [comment]
Not exactly what I'd refer to as completed, but okay...

**Comment by kaysond** [comment]
Can we add something to the documentation about backups? I'm guessing this won't be the last time this comes up

**Comment by kaysond** [comment]
Unfortunately I don't have the luxury of spending my time on a "we can consider it", sorry.

> we expect users to responsibly implement their own backup strategy

But you also expect that they can't figure out basic Linux permissions so all lsio containers forcibly chown/chmod `/config`...?

---
I don't necessarily think you're doing this deliberately, but FYI your comments all read with an air of superiority and an anti-community attitude that's disappointing for an org that essentially exists to serve the community.

**Comment by drizuid** [comment]
> all read with 
This implies that this is how YOU read it and interpret it. I just type words. If you can't take the time to submit a PR for a change, I'm unsure why you would expect us to do so. Have a wonderful day!
